# 讀資料集

In [1]:
import pandas as pd

df = pd.read_excel('../data/all.xlsx')
df.head()

,ID,Article,Question,Option1,Option2,Option3,Option4,Answer
0,1,明年元旦起，交通部新規定，汽車輪胎胎紋深度將納入定期檢驗項目之一，一旦深度未達1.6公厘，及...,汽車胎紋未到達多少公厘將會被吊銷牌照?,1.5公厘,1.4公厘,1.3公厘,1.6公厘,4
1,2,塑化劑是一種「環境荷爾蒙」，又稱內分泌干擾物，指會干擾生物體內分泌之外因性化學物質。若長時間...,若長時間使用哪一種塑化劑會使男嬰生殖器發育不良、女童性早熟，以及成年男性精蟲減少等問題。,DEHP,DINP,DNOP,DIDP,1
2,3,紐西蘭的海岸邊近日出現數百具「小藍企鵝」的屍體，專家指出，這些企鵝都是被活活餓死的，會有企鵝...,使此處海水變暖的原因為何?,洋流,全球暖化,反聖嬰現象,核能電廠排放廢水,3
3,4,綜合報導，科學期刊《當代生物學》昨天刊登一份美澳聯合研究，研究指出，近年澳洲大堡礁北部的新出...,為甚麼雄性海龜出生率降低，雌性海龜出生率則升高?,機率問題,全球暖化,環境賀爾蒙影響,當地環境影響,2
4,5,花蓮強震發生後，是否還可能發生更大的地震？中央大學地科系教授馬國鳳警告，昨晚花蓮強震應該是主...,這次花蓮大地震主要是哪一地震斷層所影響?,奇美斷層,米崙斷層,玉里斷層,嶺頂斷層,2

In [2]:
df.shape

(8550, 8)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8550 entries, 0 to 8549
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        8550 non-null   int64
 1   Article   8550 non-null   object
 2   Question  8550 non-null   object
 3   Option1   8550 non-null   object
 4   Option2   8549 non-null   object
 5   Option3   8550 non-null   object
 6   Option4   8550 non-null   object
 7   Answer    8550 non-null   int64
dtypes: int64(2), object(6)
memory usage: 534.5+ KB

In [4]:
selection = ['Option1','Option2','Option3','Option4']
selection.index('Option2')

1

# 統計標準答案是否會出現在文章中¶

In [13]:
import numpy as np
import pandas as pd

df = pd.read_excel('../data/all.xlsx')

selection = ['Option1','Option2','Option3','Option4']

# how many selections in text
count_dict = {0:0, 1:0, 2:0, 3:0, 4:0}

# how many selections in text and correct answer in the selections
corre_dict = {0:0, 1:0, 2:0, 3:0, 4:0}

count = 0

for i in range(df.shape[0]):
    rec = df.iloc[i]
    
    sel = 0
    cor = 0
    
    for s in selection:
        if str(rec[s]).lower() in str(rec['Article']).lower():
            if selection.index(s) + 1 == rec['Answer']:
                cor = 1 # s is correct answer and in text 
                
            sel = sel + 1
            
    count_dict[sel] = count_dict[sel] + 1
    corre_dict[sel] = corre_dict[sel] + cor
    
    if sel > 0:
        count = count + 1
    else:
        print(rec)
            
print(count)

for i in count_dict:
    if i > 0:
        print(i, count_dict[i], '\t', np.round(count_dict[i]/count*100, 2), '%', '\t', np.round(corre_dict[i]/count*100, 2), '%')

ID                                                          4
Article     綜合報導，科學期刊《當代生物學》昨天刊登一份美澳聯合研究，研究指出，近年澳洲大堡礁北部的新出...
Question                             為甚麼雄性海龜出生率降低，雌性海龜出生率則升高?
Option1                                                  機率問題
Option2                                                  全球暖化
Option3                                               環境賀爾蒙影響
Option4                                                當地環境影響
Answer                                                      2
Name: 3, dtype: object
ID                                                          6
Article     牛頓第一運動定律是『慣性定律』，除非物體有受到外力，要不然保持靜止的物體，會一直保持靜止；沿...
Question                                         何者為牛頓第三運動定律?
Option1                                    搭乘公車時車子突然煞車身體會向前傾斜
Option2               用手垂打牆壁時打的越用力手越痛,因為手給牆壁作用力時,同時牆也給手一個反作用力
Option3                                           搖動蘋果果樹蘋果會掉下
Option4                 同樣一台車以不同速度行駛,速度越快,撞到物品時損壞的越嚴重,因為受的力較大
Answer                                                      2
Name: 5, dtype: object
ID                                                         10
Article     九一一襲擊事件是繼第二次世界大戰日本以大型潛艇搭載的水上飛機和「氣球炸彈」空襲美國後，美國本...
Question                                         九一一事件共多少人傷亡?
Option1                                                  2996
Option2                                                  2749
Option3                                                  2846
Option4                                                  2956
Answer                                                      1
Name: 9, dtype: object
ID                                                         12
Article     1947年2月27日，專賣局查緝員在臺北市天馬茶房前查緝私菸，因不當使用公權力造成民眾一死一...
Question                               行政院公布二二八事件總計死亡人數大約多少人?
Option1                                           12000-15000
Option2                                             7000-9000
Option3                                           18000-28000
Option4                                           30000-40000
Answer                                                      3
Name: 11, dtype: object
ID                                                         13
Article     立法院經濟委員會今天修正《動物保護法》，加重虐待動物的罰則，未來若宰殺、故意傷害或使動物遭受...
Question    修正動保法後，故意傷害或使動物遭受傷害、嚴重殘缺者，將處以二年以下有期徒刑或拘役，併科新台幣...
Option1                                                20-200
Option2                                                50-500
Option3                                                30-300
Option4                                                40-400
Answer                                                      1
Name: 12, dtype: object
ID                                                         14
Article     立法院經濟委員會今天修正《動物保護法》，加重虐待動物的罰則，未來若宰殺、故意傷害或使動物遭受...
Question                           下列何項事件違者將處3千元以上1萬5千元以下的罰鍰。
Option1                                               未將排泄物帶走
Option2                                             放任寵物在路上奔跑
Option3                                                  鬥狗行為
Option4                                           飼主不得以機車牽引寵物
Answer                                                      4
Name: 13, dtype: object
ID                                                         15
Article     玉山，通常是指玉山主峰，海拔3,952公尺，為台灣最高峰。主峰為臺灣最高的山，位於南投縣信義...
Question                                      2018年玉山高度為多少公尺?
Option1                                                  3981
Option2                                                  3952
Option3                                                  3946
Option4                                                  3948
Answer                                                      2
Name: 14, dtype: object
ID                                                         19
Article     聖母峰，中文簡稱珠峰，尼泊爾名薩加瑪塔峰，為地球第一高峰，屬於喜馬拉雅山脈，位於中國西藏自治...
Question                  珠峰為世界第一高峰，它的高度為多少公尺?(以中國國家測繪局測量的為準)
Option1                                                  8842
Option2                                                  8843
Option3                                                  8844
Option4                                                  8845
Answer                                                      3
Name: 18, dtype: object
ID                                                         22
Article     花東縱谷是位於台灣東部的一個縱谷，因橫跨花蓮、台東兩縣而得名，也是上述兩縣的精華地帶所在。有...
Question                                      花東縱谷是哪兩大板塊擠壓形成?
Option1                                                太平洋、歐亞
Option2                                                菲律賓、歐亞
Option3                                               太平洋、非律賓
Option4                                               菲律賓、印度洋
Answer                                                      2
Name: 21, dtype: object
ID                                                         26
Article     東日本大震災是指日本在2011年3月11日發生的東北地方太平洋近海地震、及其伴隨而來的海嘯與...
Question                                    311大地震造成多少人死亡和失蹤?
Option1                                                 10000
Option2                                                 11000
Option3                                                 12000
Option4                                                 13000
Answer                                                      2
Name: 25, dtype: object
ID                                                         29
Article     \n\n美國牛肉分級\n美國農業部將牛肉品質分為以下等級：\n\n美國極佳級（U.S. Pr...
Question                      美國農業部將牛肉品質分為多種，請問下列舉例何者為最高級之牛肉?
Option1                                     美國特選級（U.S.Choice）
Option2                                      美國極佳級（U.S.Prime）
Option3                                     美國上選級（U.S.Select）
Option4                                 美國商用級（U.S.Commercial）
Answer                                                      2
Name: 28, dtype: object
ID                                                         30
Article     來自泰坦星的薩諾斯戴上「無限手套」親自出馬奪取六顆「無限寶石」，其意欲蒐集完「無限寶石」後彈...
Question                             請問《復仇者聯盟3》之中薩諾斯擁有幾顆無限寶石?
Option1                                                     3
Option2                                                     4
Option3                                                     5
Option4                                                     6
Answer                                                      4
Name: 29, dtype: object
ID                                                         33
Article     陳之漢（1979年3月12日－），臺灣部落客、網路名人、退伍志願役士官、企業家、運動員、健身...
Question                                 請問館長(陳之漢)開的健身中心是哪一間?
Option1                                                 300壯士
Option2                                                  健身工廠
Option3                                                  成吉斯汗
Option4                                              WorldGYM
Answer                                                      3
Name: 32, dtype: object
ID                                                         34
Article     地震（英語：Earthquake）震動，可由自然現象如地殼突然運動、火山活動及隕石撞擊引起，...
Question                                       請問地震誘因不包含下列何者?
Option1                                                  板塊擠壓
Option2                                                  火山爆發
Option3                                                  地層崩塌
Option4                                                    下雨
Answer                                                      4
Name: 33, dtype: object
ID                                                         37
Article     感覺屬於認識的感性階段，是一切知識的源泉；它同知覺緊密結合，為思維活動提供材料；感覺因分析器...
Question                                        請問感覺不是依靠哪個部位?
Option1                                                  感知器官
Option2                                                     腦
Option3                                                    神經
Option4                                                    血管
Answer                                                      4
Name: 36, dtype: object
ID                                                         38
Article     肌肉是由最基本的肌肉纖維構成，而力量訓練就是將所鍛鍊部位的肌肉纖維產生細微的破壞，受傷的肌肉...
Question                                           請問肌肉形成原理是?
Option1                                                    吃肉
Option2                                               肌肉破壞後修復
Option3                                                  攝取脂肪
Option4                                                    打藥
Answer                                                      2
Name: 37, dtype: object
ID                                           48
Article     首先要介紹的是漆的種類，可分為三大類：琺瑯漆、硝基漆、水性漆(壓克力)
Question                             漆的種類可分為幾大類
Option1                                       3
Option2                                       5
Option3                                       7
Option4                                       9
Answer                                        1
Name: 47, dtype: object
ID                                                         49
Article     黑寡婦脈衝星於 1988 年發現，是一顆和棕矮星以軌道週期 9.2 小時互繞組成食雙星的毫秒...
Question                                      黑寡婦脈衝星每秒旋轉超過幾次?
Option1                                                  100次
Option2                                                 100萬次
Option3                                                  600次
Option4                                                 6000次
Answer                                                      3
Name: 48, dtype: object
ID                                                         59
Article     前陣子電信三雄分別推出499吃到飽方案，吸引民眾爭相搶辦，但因為電信業者營運不當，造成多種亂...
Question                                           請問電信三雄分別是?
Option1                                         中華電信、遠傳及台灣大哥大
Option2                                    國家通訊傳播委員會、遠傳及台灣大哥大
Option3                                         電信業者、遠傳及台灣大哥大
Option4                                           中華電信、遠傳及NCC
Answer                                                      1
Name: 58, dtype: object
ID                                                         62
Article     近年來，國內新住民已超過50萬人，目前中小學每10個學生中就有1位是新住民子女，新住民子女已...
Question                                   為什麼新住民子女常經歷生活適應問題?
Option1                                              台灣教育環境不佳
Option2                                               人數超過50萬
Option3                                        語言文化的隔閡及社經背景弱勢
Option4                                               人數超過10萬
Answer                                                      3
Name: 61, dtype: object
ID                                                         66
Article     時序進入二十四節氣中的「小滿」，代表炎炎夏日即將到來，台北市客家主題公園特別邀請民眾，在園區...
Question                              二十四節氣中的「小滿」，代表哪個季節即將到來?
Option1                                                    冬天
Option2                                                    春天
Option3                                                    夏天
Option4                                                    秋天
Answer                                                      3
Name: 65, dtype: object
ID                                                         70
Article     挪威百年企業化肥公司亞拉國際正計劃與孔斯堡海事合作，建造 237 英尺長的電池動力無人電動貨...
Question    「亞拉伯克蘭號」（YARA Birkeland）預計下水後將沿著峽灣航行 30 海浬在兩個港...
Option1                                                    4萬
Option2                                                    6萬
Option3                                                    3萬
Option4                                                    5萬
Answer                                                      1
Name: 69, dtype: object
ID                                                         85
Article     腸病毒蠢蠢欲動！2018年新北市已確診4例腸病毒感染併發重症，年齡皆小於5歲。提醒民眾提高警...
Question                              新北市衛生局監測，上週腸病毒門急診就診有多少人
Option1                                                  1121
Option2                                                  1111
Option3                                                  1211
Option4                                                  2111
Answer                                                      3
Name: 84, dtype: object
ID                                                        118
Article     對期望提升人工智慧圖像辨識能力的企業來說，如何自建深度學習模型，以及如何訓練模型來優化圖像辨...
Question                                    請問優化圖像辨識精準度的兩大祕訣?
Option1                                                 冥想與睡覺
Option2                                           自建與訓練深度學習模型
Option3                                                 許願與拜佛
Option4                                                 睡覺與吃飯
Answer                                                      2
Name: 117, dtype: object
ID                                                        119
Article     所謂的 5G 通訊指的並非是具體的單一技術，而是第 5 代行動通訊網路（5th Genera...
Question                                      請問5G是第幾代行動通訊技術?
Option1                                                   第3代
Option2                                                   第4代
Option3                                                   第5代
Option4                                                   第2代
Answer                                                      3
Name: 118, dtype: object
ID                                                        123
Article     2016 年堪稱「直播元年」，中國兩百家多家獲得融資的網路公司這兩年已經燒了不知多少錢，純粹...
Question                                     「直播答題」的創新性和定位為何?
Option1                                                  因為好玩
Option2                                             達成特定的行銷價值
Option3                                                  娛樂效果
Option4                                                   做慈善
Answer                                                      2
Name: 122, dtype: object
ID                                                        124
Article     當大家完成第一波「撒錢」後，自然要開始評估成效，到底專門靠舉辦答題能否實現營利；高額獎金，快...
Question                                       「直播答題」的商業模式為何?
Option1                                                盜取用戶資料
Option2                                                吸收玩家金錢
Option3                                                  賺廣告費
Option4                                                    洗錢
Answer                                                      3
Name: 123, dtype: object
ID                                                        125
Article     這一次「直播答題」的熱潮，基本是由中國政府的管制措施澆熄，認為許多平台在宣傳上，在題目內容上...
Question                                    「直播答題」良性運行需要那些條件?
Option1                                               不影響國家法規
Option2                                                   土豪哥
Option3                                                 有錢的用戶
Option4                                                    金錢
Answer                                                      1
Name: 124, dtype: object
ID                                                        127
Article     所謂的「潮汕幫」是傳統三大商幫之一，在商界夙負盛名，如長江集團李嘉誠、騰訊馬化騰及星河集團黃...
Question                                               何謂潮汕幫?
Option1                                                  台灣黑幫
Option2                                                  香港黑幫
Option3                                 潮汕幫是傳統三大商幫之一，在商界夙負盛名。
Option4                                                 日本山口組
Answer                                                      3
Name: 126, dtype: object
ID                                                        128
Article     根據 NCC 公布 2017 年第四季的數據，從國內 5 家電信業者的行動電話用戶數市占率來...
Question                                   請問2017年第四季中華電信市占率?
Option1                                                   0.5
Option2                                                 0.364
Option3                                                 0.283
Option4                                                 0.425
Answer                                                      2
Name: 127, dtype: object
ID                                                        130
Article     數據顯示，全國行動電話總用戶數約為 2,866 萬戶，普及率約為 121%，當中，3G 用戶...
Question                                       全國行動電話用戶數約為多少?
Option1                                                 1800萬
Option2                                                 2300萬
Option3                                                 2866萬
Option4                                                  500萬
Answer                                                      3
Name: 129, dtype: object
ID                                                        142
Article     基隆因地緣關係，發展出郵輪服務，常聚集許多國際郵輪旅客，但旅客下船後多半直接往臺北而去，造成...
Question                                         基隆市如何帶動觀光發展?
Option1                                                留住國際旅客
Option2                                                    販毒
Option3                                                 塞錢給旅客
Option4                                                  綁架旅客
Answer                                                      1
Name: 141, dtype: object
ID                                                        146
Article     為展現政府開放資料品質，臺中市政府與景翊科技公司共同開發「Easy Traffic 簡單交通...
Question                           臺中市如何完善 Easy Traffic 簡單交通?
Option1                                                    花錢
Option2                                                   不管他
Option3                                                    隨緣
Option4                                                  回饋功能
Answer                                                      4
Name: 145, dtype: object
ID                                                        157
Article     最新研究顯示，天天喝代糖飲料的人，罹患梗塞性腦中風和阿茲海默症的風險是常人的3倍；若每週喝1...
Question                                            下列敘述何者正確?
Option1                               每週喝1次代糖飲料，腦中風風險會增加2.62倍
Option2                                常喝含蔗糖飲料者，腦中風和失智症風險明顯提高
Option3                             每週喝1次代糖飲料，腦中風風險也比一般人多出約3倍
Option4                                           代糖飲料比含糖飲料健康
Answer                                                      1
Name: 156, dtype: object
ID                                                        170
Article     歐洲聯盟執行委員會今天表示，將向歐洲聯盟法院狀告德國、法國、英國及另三個歐盟成員國，因為他們...
Question                                         在今年幾月給予最後機會?
Option1                                                    5月
Option2                                                    7月
Option3                                                    4月
Option4                                                    1月
Answer                                                      4
Name: 169, dtype: object
ID                                                        176
Article     外賣替生活帶來便利的同時，也製造了巨量的垃圾，統計顯示，中國每天消耗的餐盒超過6,000萬個...
Question                                         每天消耗超過多少個餐盒?
Option1                                                 6000萬
Option2                                                 7000萬
Option3                                                 8000萬
Option4                                                 9000萬
Answer                                                      1
Name: 175, dtype: object
ID                                                        196
Article     環保、綠能已成全球趨勢，台灣為推動非核家園，正在積極發展風力發電。而同樣有空污、核電廠老化問...
Question                                南韓預定要在哪一年年拉高整體能源使用占比?
Option1                                                 2015年
Option2                                                 2020年
Option3                                                 2025年
Option4                                                 2030年
Answer                                                      4
Name: 195, dtype: object
ID                                                        197
Article     環保、綠能已成全球趨勢，台灣為推動非核家園，正在積極發展風力發電。而同樣有空污、核電廠老化問...
Question                                        要將目前的7%拉高至多少?
Option1                                                   0.1
Option2                                                   0.2
Option3                                                 0.638
Option4                                                 0.203
Answer                                                      2
Name: 196, dtype: object
ID                                                        198
Article     愛立信的調查顯示，只有 4% 的受訪者相信營運商的廣告及網路效能的宣傳，消費者希望營運商摒棄...
Question                     根據愛立信的調查顯示幾%的受訪者相信營運商的廣告及網路效能的宣傳
Option1                                                  0.01
Option2                                                   0.5

In [6]:
import unicodedata

def longest_common_substrings(s1: str, s2: str):
    """
    回傳 (最長長度, 最長子字串列表[去重後排序])
    """
    # 正規化，避免全形/組合字等 Unicode 差異
    #s1 = unicodedata.normalize('NFC', s1)
    #s2 = unicodedata.normalize('NFC', s2)

    n, m = len(s1), len(s2)
    if n == 0 or m == 0:
        return 0, []

    # dp[j] 代表以 s1[:i] 與 s2[:j] 結尾的最長共同"連續"長度
    prev = [0] * (m + 1)
    best_len = 0
    best_set = set()

    for i in range(1, n + 1):
        cur = [0] * (m + 1)
        for j in range(1, m + 1):
            if s1[i - 1] == s2[j - 1]:
                cur[j] = prev[j - 1] + 1
                if cur[j] > best_len:
                    best_len = cur[j]
                    best_set = {s1[i - best_len:i]}
                elif cur[j] == best_len and best_len > 0:
                    best_set.add(s1[i - best_len:i])
        prev = cur

    return best_len, sorted(best_set)

# 範例
a = "我在臺灣大學讀資工系"
b = "資工系的課很多，我朋友也在臺灣大學讀資工系"
a = "若滿分為100，請問哪個是滿分"
b = "100"
length, substrings = longest_common_substrings(a, b)
print("最長長度：", length)        # 例如輸出 3
print("最長片段：", substrings)    # 例如輸出 ['資工系']

最長長度： 3
最長片段： ['100']

# 統計標準答案是否會出現在文章中

In [13]:
import numpy as np
import pandas as pd

df = pd.read_excel('../data/all.xlsx')

selection = ['Option1','Option2','Option3','Option4']

# how many selections in text
count_dict = {0:0, 1:0, 2:0, 3:0, 4:0}

# how many selections in text and correct answer in the selections
corre_dict = {0:0, 1:0, 2:0, 3:0, 4:0}

count = 0

for i in range(df.shape[0]):
    rec = df.iloc[i]
    
    sel = 0
    cor = 0
    
    for s in selection:
        length, _ = longest_common_substrings(str(rec[s]).strip().lower(), str(rec['Article']).strip().lower())
        if length >= 1:
            if selection.index(s) + 1 == rec['Answer']:
                cor = 1 # s is correct answer and in text 
                
            sel = sel + 1
            
    count_dict[sel] = count_dict[sel] + 1
    corre_dict[sel] = corre_dict[sel] + cor
    
    if sel > 0:
        count = count + 1
    else:
        print(rec)
            
print(count)

for i in count_dict:
    if i > 0:
        print(i, count_dict[i], '\t', np.round(count_dict[i]/count*100, 2), '%', '\t', np.round(corre_dict[i]/count*100, 2), '%')

ID                                                         30
Article     來自泰坦星的薩諾斯戴上「無限手套」親自出馬奪取六顆「無限寶石」，其意欲蒐集完「無限寶石」後彈...
Question                             請問《復仇者聯盟3》之中薩諾斯擁有幾顆無限寶石?
Option1                                                     3
Option2                                                     4
Option3                                                     5
Option4                                                     6
Answer                                                      4
Name: 29, dtype: object
ID                                           48
Article     首先要介紹的是漆的種類，可分為三大類：琺瑯漆、硝基漆、水性漆(壓克力)
Question                             漆的種類可分為幾大類
Option1                                       3
Option2                                       5
Option3                                       7
Option4                                       9
Answer                                        1
Name: 47, dtype: object
ID                                                        209
Article     張嘴就喊語音助理要它幹活，可能會給你「我就是鋼鐵人」的錯覺。希望你還沒對它們產生深度依賴，因...
Question                                           成功率甚至高達多少%
Option1                                                  0.25
Option2                                                     0
Option3                                                     1
Option4                                                   0.5
Answer                                                      3
Name: 208, dtype: object
ID                         290
Article     彩虹有七種顏色，分別是紅橙黃綠藍靛紫
Question               彩虹有幾種顏色
Option1                      4
Option2                      5
Option3                      6
Option4                      7
Answer                       4
Name: 289, dtype: object
ID                              291
Article     中國有十二生肖，分別為鼠牛虎兔龍蛇馬羊猴雞狗豬
Question                    中國有多少生肖
Option1                          11
Option2                          12
Option3                          13
Option4                          14
Answer                            2
Name: 290, dtype: object
ID                    303
Article                同上
Question    哥哥今年100歲，弟弟幾歲
Option1                48
Option2                50
Option3                98
Option4               100
Answer                  3
Name: 302, dtype: object
ID                              304
Article     星期一時我右手伸出一根手指，每過一天我多伸一隻
Question                七天後我右手有幾根手指
Option1                           4
Option2                           5
Option3                           6
Option4                           7
Answer                            2
Name: 303, dtype: object
ID                      319
Article       有位天才，擅長的科目都滿分
Question    若滿分為100，請問哪個是滿分
Option1                  99
Option2                  98
Option3                 100
Option4                99.1
Answer                    3
Name: 318, dtype: object
ID                                                        401
Article     日本大阪府北部十八日上午七時五十八分發生芮氏規模六．一強震，關西地區均感受到劇烈搖晃，由於正...
Question                                          請問此次地震芮氏規模?
Option1                                                   4.1
Option2                                                   5.1
Option3                                                   6.1
Option4                                                   7.1
Answer                                                      3
Name: 400, dtype: object
ID                                                        763
Article     《推背圖》是中華預言書中最為著名的奇書之一，相傳是唐朝貞觀年間，由預言大師李淳風和袁天罡對唐...
Question                                        請問推背圖總共有多少圖像？
Option1                                                    40
Option2                                                    50
Option3                                                    60
Option4                                                    70
Answer                                                      3
Name: 762, dtype: object
ID                                                        890
Article     中國人壽積極推動公司治理與風險管理，在超過800多家上市公司的競爭下，連續四年榮獲於台灣證券...
Question    中國人壽積極推動公司治理與風險管理，在超過800多家上市公司的競爭下，連續幾年榮獲於台灣證券...
Option1                                                     1
Option2                                                     2
Option3                                                     3
Option4                                                     4
Answer                                                      4
Name: 889, dtype: object
ID                                                        893
Article     全台用電量自周一起連三日刷下今年新高，昨日還擠上歷史5月用電量第二高，今日依舊炎熱高溫，台電...
Question                                 今年全台用電量是歷史5月用電量排名第幾？
Option1                                                     1
Option2                                                     2
Option3                                                     3
Option4                                                     4
Answer                                                      2
Name: 892, dtype: object
ID                                                        961
Article     一九五○年六月廿五日爆發的韓戰，持續三年。一九五三年七月廿七日簽署的「韓戰停戰協定」，由當時...
Question                                            韓戰在西元幾年開戰
Option1                                                  1900
Option2                                                  1950
Option3                                                  1990
Option4                                                  2000
Answer                                                      2
Name: 960, dtype: object
ID                                                       1317
Article     世界衛生組織將「電玩失調症」納入「國際疾病分類」第十一修訂版中，致使電玩成癮成為臨床上的精神...
Question                    請問世界衛生組織將「電玩失調症」納入「國際疾病分類」第幾版修訂版?
Option1                                                    10
Option2                                                    11
Option3                                                    12
Option4                                                    13
Answer                                                      2
Name: 1316, dtype: object
ID                                         1328
Article     中華民國五權分立，五院中分別有行政院、立法院、司法院、監察院、考試院。
Question                            請問中華民國有幾個院?
Option1                                      3個
Option2                                      4個
Option3                                      5個
Option4                                      6個
Answer                                        3
Name: 1327, dtype: object
ID                                                       1330
Article     《空氣人形》（日語：空気人形），是一部日本電影，由業田良家的同名漫畫改編、是枝裕和執導。故事...
Question                                       請問電影的日語名字有幾個字?
Option1                                                     4
Option2                                                     8
Option3                                                    12
Option4                                                    16
Answer                                                      1
Name: 1329, dtype: object
ID                                                       1392
Article     證券櫃檯買賣中心預計於107年5月3日召開上櫃審議委員會，審議茂生農經申請上櫃案。\n\n茂...
Question                      根據短文資訊，105年至106年間茂生農經的營業收入有何變化？
Option1                                                    增加
Option2                                                    減少
Option3                                                  維持不變
Option4                                                    歸零
Answer                                                      1
Name: 1391, dtype: object
ID                                                       1393
Article     證券櫃檯買賣中心預計於107年5月3日召開上櫃審議委員會，審議茂生農經申請上櫃案。\n\n茂...
Question                      根據短文資訊，105年至106年間茂生農經的稅後淨利有何變化？
Option1                                                    增加
Option2                                                    減少
Option3                                                  維持不變
Option4                                                    歸零
Answer                                                      2
Name: 1392, dtype: object
ID                                                       1394
Article     證券櫃檯買賣中心預計於107年5月3日召開上櫃審議委員會，審議茂生農經申請上櫃案。\n\n茂...
Question                      根據短文資訊，105年至106年間茂生農經的每股盈餘有何變化？
Option1                                                    增加
Option2                                                    減少
Option3                                                  維持不變
Option4                                                    歸零
Answer                                                      2
Name: 1393, dtype: object
ID                                                       1495
Article     蔡英文總統親臨警察專科學校主持警專七十一周年校慶大會，並且頒發傑出校友給移民署署長何榮村等人...
Question                                請問蔡總統參加台灣警察專科學校幾周年校慶?
Option1                                                    89
Option2                                                    61
Option3                                                    71
Option4                                                    59
Answer                                                      3
Name: 1494, dtype: object
ID                                                       1647
Article     以健保署近三年訪查情形發現，醫療院所多用不實名目詐領健保，去年詐領金額創下三年來新高，健保署...
Question                                       文章中有多少間醫療院所違規？
Option1                                                 1108家
Option2                                                 2285家
Option3                                                    3家
Option4                                                   85家
Answer                                                      1
Name: 1646, dtype: object
ID                                                       1654
Article     十七位司改籌備委員，召開司改國是會議第一次籌備委員會，確認工作進程，擔任召集人的蔡英文總統親...
Question                           有幾位司改籌備委員召開司改國是會議第一次籌備委員會？
Option1                                                    10
Option2                                                    17
Option3                                                    16
Option4                                                    15
Answer                                                      2
Name: 1653, dtype: object
ID                                                       1771
Article     高血壓、高血糖及高血脂合稱「三高」，其中高血脂最不易察覺，也就是高密度膽固醇偏低，低密度膽固...
Question                                   國內每幾分鐘就有一人因心血管疾病死亡
Option1                                                    88
Option2                                                    18
Option3                                                    19
Option4                                                    11
Answer                                                      2
Name: 1770, dtype: object
ID                                                       1827
Article     蔡英文總統1號在台灣駭客年會致詞時表示，傳統觀念裡，政府與駭客有些對立，政府必須扮演管制的角...
Question                                               政務委員是誰
Option1                                                   唐三藏
Option2                                                   唐伯虎
Option3                                                    唐鳳
Option4                                                   鳳飛飛
Answer                                                      3
Name: 1826, dtype: object
ID                                                       1919
Article     中研院今年研究發現，煮咖哩會放的薑黃裏頭有一種衍生物，可以刺激人腦內的腦啡酶酵素活性，能有效...
Question                              本篇所進口的薑黃粉，鉛含量竟然超出標準值的幾倍
Option1                                                  500倍
Option2                                                  600倍
Option3                                                  800倍
Option4                                                 1000倍
Answer                                                      3
Name: 1918, dtype: object
ID                                                       1937
Article     高雄市左營警分局文自路派出所員警,晚間11點多獲報,左營區崇德路有一部自用車就斜停在路中,員...
Question                                            嫌犯拿出甚麼當證件
Option1                                                    證件
Option2                                                   撲克牌
Option3                                                    名片
Option4                                                    卡片
Answer                                                      2
Name: 1936, dtype: object
ID                                           2418
Article            早期只有男性才具有投票權，經過多年的努力，婦女也享有投票權。
Question    這項投票情形的轉變，若依我國憲\n法的規定來看，主要象徵何項選舉原則的落實
Option1                                        普通
Option2                                        平等
Option3                                        直接
Option4                                       無記名
Answer                                          1
Name: 2417, dtype: object
ID                                                       2426
Article     近年來的電視戲劇節目以不同時代的人物穿越古今，因生活背景差異所產生的劇情跌宕，吸引觀眾。編劇...
Question                           下列各組人物腳色的搭配，何者最不符合所謂的「穿越」？
Option1                                                 李白與杜甫
Option2                                                 項羽與關羽
Option3                                               王安石與康有為
Option4                                               顏真卿與關漢卿
Answer                                                      1
Name: 2425, dtype: object
ID                                            2428
Article     葉似蒲而短闊，兩旁如鋸齒。其實色黃，瓤如鱗甲，形似甜瓜。味甚甘酸，清芬襲人。
Question                               上文所描述的水果\n是
Option1                                         芒果
Option2                                         鳳梨
Option3                                        火龍果
Option4                                        百香果
Answer                                           2
Name: 2427, dtype: object
ID                                                       2435
Article     2005 年近千名南韓農民為了抗議美國等國家對自家出產的農產品提供補貼，並以低價傾銷到南韓，...
Question                                        該項抗議是屬於下列何種訴求
Option1                                                   本土化
Option2                                                  反全球化
Option3                                                 在地全球化
Option4                                                 全球在地化
Answer                                                      2
Name: 2434, dtype: object
ID                                                2438
Article     東北季風盛行時，臺灣會出現沙塵暴，主要是因為蒙古地區的草原被游牧民族過度使用的結果。
Question                     草原因具有下列那一種特性，而導致游牧民族過度使用？
Option1                                            公共財
Option2                                            私有財
Option3                                            劣等財
Option4                                            共有財
Answer                                               4
Name: 2437, dtype: object
ID                              2447
Article     民眾不假他人之手，親自前往投票支持心目中的候選人
Question                 此乃落實下列何項原則？
Option1                         普通原則
Option2                         平等原則
Option3                         直接原則
Option4                        無記名原則
Answer                             3
Name: 2446, dtype: object
ID                     2463
Article       書法刻於石碑者稱之為「碑」
Question    下列選項何者與碑刻文化完全無關
Option1                  臨摹
Option2                  尺牘
Option3                  拓本
Option4                  鑑賞
Answer                    2
Name: 2462, dtype: object
ID                                                       2487
Article     你坐在船上，應該是游山的態度。看看四周物色，隨處可見的山，岸旁的烏桕，河邊的紅蓼和白蘋，漁舍...
Question                                             本段文字旨在強調
Option1                                                  知情識趣
Option2                                                  參觀博覽
Option3                                                  閒情逸致
Option4                                                  林下風致
Answer                                                      3
Name: 2486, dtype: object
ID                                                       2674
Article     屏東縣枋山鄉刺桐路口,6號上午一連發生三起車禍,造成七輛車受損,四人受傷車禍原因,員警初步調...
Question                                        同個路口共發幾起交通事故？
Option1                                                     2
Option2                                                     3
Option3                                                     4
Option4                                                     5
Answer                                                      2
Name: 2673, dtype: object
ID                                                       3077
Article     您中獎了嗎？全民國防網際網路路有獎徵答活動上個月熱鬧舉行，國防部今天上午在三軍救災英雄、律師...
Question                                          請問總共有多少個獎項？
Option1                                                    60
Option2                                                    37
Option3                                                   460
Option4                                                   640
Answer                                                      4
Name: 3076, dtype: object
ID                                                       3245
Article     操在兗州，招賢納士。有叔姪二人來投曹操：乃穎川穎陰人：姓荀，名彧，字文若，荀昆之子也；舊事袁...
Question                                請問旬彧和旬攸兩人到曹操手下，曹操的心情?
Option1                                                    開心
Option2                                                    難過
Option3                                                    憤怒
Option4                                                    傷心
Answer                                                      1
Name: 3244, dtype: object
ID                                                       3410
Article     誰知自在此間住了不上一月的光景，賈宅族中凡有的子侄，俱已認熟了一半，凡是那些紈氣習者，莫不喜...
Question                                       賈政管束不了薛蟠有幾個理由？
Option1                                                     1
Option2                                                     2
Option3                                                     3
Option4                                                     4
Answer                                                      3
Name: 3409, dtype: object
ID                                                       3830
Article     大仙請觀音見了，觀音說：“還是先醫寶樹要緊。”眾人來到人參園，菩薩讓悟空伸出手，用楊柳枝蘸淨...
Question                                 請問樹活過來的時候，上面掛了幾個人參果?
Option1                                                    20
Option2                                                    21
Option3                                                    22
Option4                                                    23
Answer                                                      4
Name: 3829, dtype: object
ID                                                       3843
Article     悟空請唐僧吃了桃，扶他上馬，再往西走。那怪豈肯甘心?又變成一個白髮蒼蒼的老婆婆，手拄一根竹杖...
Question                                         請問唐僧念緊箍咒多少遍?
Option1                                                    20
Option2                                                    30
Option3                                                    40
Option4                                                    50
Answer                                                      1
Name: 3842, dtype: object
ID                                                       3846
Article     那妖精在半空中恨得咬牙切齒，這猴頭果然名不虛傳，手段高強，若不是猴頭，唐僧早成了他口中食了。...
Question                                       請問還有多遠便出了妖精地盤?
Option1                                                   40尺
Option2                                                   40里
Option3                                                   40丈
Option4                                                   40寸
Answer                                                      2
Name: 3845, dtype: object
ID                                                       3852
Article     忽然，從荒草叢中，荊棘棵裡，跳出幾隻猴子來，跪拜說：“大聖爺爺，你可回來了。”猴王問：“這是...
Question                                       請悟空回來前家中共有幾位元帥
Option1                                                     2
Option2                                                     4
Option3                                                     5
Option4                                                     6
Answer                                                      1
Name: 3851, dtype: object
ID                                                       3894
Article     悟空說：“我臨別時一再叮嚀，逢上妖魔提我老孫的名號，你們怎麼不提了?”八戒急中生智，說：“怎...
Question                                      請問大聖安排幾隻老猴看守洞府?
Option1                                                    1隻

In [3]:
import re
from cn2an import cn2an

def parse_cn_or_percent(s: str):
    s = s.strip()
    
    # 處理 “百分之X” 類型
    m = re.match(r"百分之(.+)", s)
    if m:
        inner = m.group(1)
        num = cn2an(inner, "smart")
        value = float(num) / 100.0
    # 處理帶 % 的情況
    elif "%" in s:
        s2 = s.replace("%", "")
        try:
            num = float(s2)
        except ValueError:
            num = cn2an(s2, "smart")
        value = float(num) / 100.0
    # 無百分比的情況
    else:
        try:
            value = float(s)
        except ValueError:
            value = float(cn2an(s, "smart"))
    
    # 若是整數，轉成 int
    if value.is_integer():
        return int(value)
    return value

# 測試
tests = ["一百二十三", "二十五", "百分之五十", "百分之一百", "100%", "0.5", "三點五"]
for t in tests:
    print(f"{t} → {parse_cn_or_percent(t)}")

一百二十三 → 123
二十五 → 25
百分之五十 → 0.5
百分之一百 → 1
100% → 1
0.5 → 0.5
三點五 → 3.5

In [4]:
import re
from cn2an import cn2an

# ===== 1) 你的核心轉換函式 =====
def parse_cn_or_percent(s: str):
    s = s.strip()
    m = re.match(r"百分之\s*(.+)", s)
    if m:  # 「百分之X」
        inner = m.group(1)
        num = _to_number(inner)
        value = float(num) / 100.0
    elif "%" in s:  # 「X%」
        s2 = s.replace("%", "").strip()
        num = _to_number(s2)
        value = float(num) / 100.0
    else:  # 純數字（中文/阿拉伯）
        value = float(_to_number(s))
    # 整數不加 .0
    return int(value) if value.is_integer() else value

def _to_number(token: str):
    # 嘗試阿拉伯 → 否則中文（smart 自動判斷繁簡/大小寫數字）
    try:
        return float(token)
    except ValueError:
        # 支援「負/负」與「點/点」等中文小數
        # cn2an 會處理「兩、壹、貳…」等多種數字寫法
        return float(cn2an(token, "smart"))

# ===== 2) 全文替換器 =====
# 你可以把想處理的型態拆成三個 pattern，依序替換，避免重覆處理
PAT_PERCENT_ZH = re.compile(
    r"百分之\s*([+\-]?[0-9\.零〇一二兩三四五六七八九十百千萬亿億兆點点壹貳參肆伍陸柒捌玖负負]+)"
)
PAT_PERCENT_SYM = re.compile(
    r"([+\-]?[0-9\.零〇一二兩三四五六七八九十百千萬亿億兆點点壹貳參肆伍陸柒捌玖负負]+)\s*%"
)
# 盡量避免吃到小數點左右的阿拉伯數字；只針對純中文數字片段
PAT_CN_NUM = re.compile(
    r"(?<![\d\.])([负負]?[零〇一二兩三四五六七八九十百千萬亿億兆壹貳參肆伍陸柒捌玖]+(?:[點点][零〇一二兩三四五六七八九壹貳參肆伍陸柒捌玖]+)?)"
    r"(?![\d\.%])"
)

def _fmt(value: float) -> str:
    # 整數 → int；浮點 → 去除多餘尾零與科學記號
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return f"{value:.15g}"

def replace_cn_numbers(text: str) -> str:
    # 1) 「百分之X」 → 轉成小數
    def repl_percent_zh(m):
        whole = "百分之" + m.group(1)
        v = parse_cn_or_percent(whole)
        return _fmt(v)

    # 2) 「X%」 → 轉成小數
    def repl_percent_sym(m):
        whole = m.group(0)
        v = parse_cn_or_percent(whole)
        return _fmt(v)

    # 3) 純中文數字 → 阿拉伯數字
    def repl_cn_num(m):
        token = m.group(1)
        v = parse_cn_or_percent(token)
        return _fmt(v)

    # 依序替換，避免互相影響
    out = PAT_PERCENT_ZH.sub(repl_percent_zh, text)
    out = PAT_PERCENT_SYM.sub(repl_percent_sym, out)
    out = PAT_CN_NUM.sub(repl_cn_num, out)

    return out

# ===== 3) 範例 =====
if __name__ == "__main__":
    s = (
        "今年營收成長百分之五、毛利率約35%，"
        "去年的成長率是3%，本季目標百分之一百。"
        "樣品數量為一百二十三，誤差三點五。"
        "負十二與負三點五也要能解析。"
    )
    print(replace_cn_numbers(s))

今年營收成長0.05、毛利率約0.35，去年的成長率是0.03，本季目標1。樣品數量為123，誤差3.5。-12與-3.5也要能解析。

In [8]:
# -*- coding: utf-8 -*-
"""
Chinese number & percentage replacer
------------------------------------
pip install cn2an

提供兩個主要API：
1) parse_cn_or_percent(s): 將單一片段（中文數字 / X% / 百分之X / 千分之X / 萬分之X）轉成數值（int或float）。
2) replace_cn_numbers(text, **options): 對整段文字做就地替換。

作者：你
"""

import re
from typing import Iterable, Pattern, Tuple
from cn2an import cn2an

# ===== 0) 規則與正規化 =====

# 單獨位階字：自動補「一」（例如「百」→「一百」，避免 cn2an 拒絕）
UNIT_ONLY = {"十", "拾", "百", "佰", "千", "仟", "萬", "万", "億", "亿", "兆"}

# 中文數字字形正規化（可按需求增減）
CN_NORMALIZE = {
    "兩": "二", "俩": "二",
    "点": "點",
    "负": "負",
    "〇": "零", "○": "零", "Ｏ": "零",
    "拾": "十", "佰": "百", "仟": "千",
    "万": "萬", "亿": "億",
}

# 量級詞（分母）：百分/千分/萬分
DENOM_WORDS = {
    "百分之": 100.0,
    "千分之": 1000.0,
    "萬分之": 10000.0,
}

# ===== 1) 解析核心 =====

def _normalize_cn_token(token: str) -> str:
    t = token.strip()
    for k, v in CN_NORMALIZE.items():
        t = t.replace(k, v)
    if t in UNIT_ONLY:
        t = "一" + t  # 對單獨位階字補「一」
    return t

def _to_number(token: str) -> float:
    """
    嘗試將 token 轉成浮點數：
    1) 先嘗試阿拉伯數字
    2) 失敗則正規化中文，再用 cn2an 解析
    解析失敗會 raise 讓外部決定是否保留原字串
    """
    token = token.strip()
    # 先試阿拉伯
    try:
        return float(token)
    except ValueError:
        pass

    # 中文
    t = _normalize_cn_token(token)
    # 特例：一十 → 10；也可直接交給 cn2an 解析（它也能處理）
    try:
        return float(cn2an(t, "smart"))
    except Exception:
        raise

def _fmt_number(value: float) -> str:
    """整數不帶 .0，浮點去除多餘尾零，不用科學記號。"""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return f"{value:.15g}"

def parse_cn_or_percent(s: str):
    """
    將單一文字片段轉為數值：
    支援：
      - 純中文數字：一百二十三 → 123
      - 小數：三點五 → 3.5
      - 負數：負三點五 → -3.5
      - 百分比：百分之五十 / 50% → 0.5
      - 千分比：千分之五 → 0.005
      - 萬分比：萬分之五 → 0.0005
    回傳 int 或 float
    """
    s = s.strip()
    # 量級詞（百分/千分/萬分）
    for word, denom in DENOM_WORDS.items():
        m = re.match(rf"{word}\s*(.+)", s)
        if m:
            inner = m.group(1)
            num = _to_number(inner)
            value = float(num) / denom
            return int(value) if value.is_integer() else value

    # X%
    if "%" in s:
        # 允許 " 99.5 % "
        s2 = s.replace("%", "").strip()
        num = _to_number(s2)
        value = float(num) / 100.0
        return int(value) if value.is_integer() else value

    # 純數字（中文/阿拉伯）
    value = float(_to_number(s))
    return int(value) if value.is_integer() else value

# ===== 2) 全文替換器 =====

# 量級詞（百分/千分/萬分） → 小數
PAT_DENOM_ZH: Pattern = re.compile(
    r"(百分之|千分之|萬分之)\s*([+\-]?[0-9\.零〇一二兩三四五六七八九十百千萬亿億兆點点壹貳參肆伍陸柒捌玖负負]+)"
)

# X%
PAT_PERCENT_SYM: Pattern = re.compile(
    r"([+\-]?[0-9\.零〇一二兩三四五六七八九十百千萬亿億兆點点壹貳參肆伍陸柒捌玖负負]+)\s*%"
)

# 純中文數字（避免吃到鄰近阿拉伯或 %）；允許負號與小數
PAT_CN_NUM: Pattern = re.compile(
    r"(?<![\d\.])"                                  # 左側不是數字或小數點
    r"([负負]?[零〇一二兩三四五六七八九十百千萬亿億兆壹貳參肆伍陸柒捌玖]+"
    r"(?:[點点][零〇一二兩三四五六七八九壹貳參肆伍陸柒捌玖]+)?)"
    r"(?![\d\.%])"                                  # 右側不是數字/小數點/%
)

# 預設的語境排除（避免把日期、年分等錯轉）
DEFAULT_EXCLUSION_PATTERNS: Tuple[Pattern, ...] = (
    # 2025年、二〇二五年、二零二五年
    re.compile(r"(?:\d{2,4}|[零〇一二兩三四五六七八九]{2,4})\s*年"),
    # 一月/二月/十二月/週一/星期一
    re.compile(r"(?:[零〇一二兩三四五六七八九十]{1,3})(?:\s*[月號日週星期])"),
    # 時間（兩點/三點五分）
    re.compile(r"(?:[零〇一二兩三四五六七八九十]{1,3})\s*點"),
)

def _is_excluded(span: Tuple[int, int], text: str, exclusions: Iterable[Pattern]) -> bool:
    """判斷匹配區段是否位於排除語境（任一排除規則在該區段附近命中）。"""
    start, end = span
    window_l = max(0, start - 6)  # 粗略取上下文視窗
    window_r = min(len(text), end + 6)
    ctx = text[window_l:window_r]
    return any(p.search(ctx) for p in exclusions)

def replace_cn_numbers(
    text: str,
    *,
    apply_denoms: bool = True,
    apply_symbol_percent: bool = True,
    apply_pure_cn: bool = True,
    exclusions: Iterable[Pattern] = DEFAULT_EXCLUSION_PATTERNS,
) -> str:
    """
    對整段文字進行替換：
        - 百分/千分/萬分之X → 小數
        - X% → 小數
        - 純中文數字 → 阿拉伯數字
    參數：
        apply_denoms: 是否處理「百分/千分/萬分之」
        apply_symbol_percent: 是否處理「X%」
        apply_pure_cn: 是否處理純中文數字
        exclusions: 語境排除的正則清單
    """
    out = text

    # 1) 量級詞（百分/千分/萬分之）
    if apply_denoms:
        def repl_denoms(m):
            # 排除語境
            if _is_excluded(m.span(), out, exclusions):
                return m.group(0)
            whole = m.group(0)
            try:
                v = parse_cn_or_percent(whole)
                return _fmt_number(v)
            except Exception:
                return whole
        out = PAT_DENOM_ZH.sub(repl_denoms, out)

    # 2) X%
    if apply_symbol_percent:
        def repl_percent_sym(m):
            if _is_excluded(m.span(), out, exclusions):
                return m.group(0)
            whole = m.group(0)
            try:
                v = parse_cn_or_percent(whole)
                return _fmt_number(v)
            except Exception:
                return whole
        out = PAT_PERCENT_SYM.sub(repl_percent_sym, out)

    # 3) 純中文數字
    if apply_pure_cn:
        # 為避免替換過程中 span 移動導致誤判，使用 finditer + 手工拼接
        parts = []
        last = 0
        for m in PAT_CN_NUM.finditer(out):
            s, e = m.span()
            token = m.group(1)
            # 排除語境
            if _is_excluded((s, e), out, exclusions):
                continue
            parts.append(out[last:s])
            try:
                v = parse_cn_or_percent(token)
                parts.append(_fmt_number(v))
            except Exception:
                parts.append(token)  # 解析失敗保留原文
            last = e
        parts.append(out[last:])
        out = "".join(parts)

    return out

# ===== 3) 範例與測試 =====
if __name__ == "__main__":
    demo = (
        "今年營收成長百分之五、毛利率約35%，"
        "去年的成長率是3%，本季目標百分之一百。"
        "樣品數量為一百二十三，誤差三點五。"
        "負十二與負三點五也要能解析。"
        "另外，千分之五、萬分之二也要轉。"
        "日期如2025年、一月、星期一不應該被轉。"
        "單獨位階字：十、百、千、萬。"
    )
    print("原文：")
    print(demo)
    print("\n替換後：")
    print(replace_cn_numbers(demo))

原文：
今年營收成長百分之五、毛利率約35%，去年的成長率是3%，本季目標百分之一百。樣品數量為一百二十三，誤差三點五。負十二與負三點五也要能解析。另外，千分之五、萬分之二也要轉。日期如2025年、一月、星期一不應該被轉。單獨位階字：十、百、千、萬。

替換後：
今年營收成長0.05、毛利率約0.35，去年的成長率是0.03，本季目標1。樣品數量為一百二十三，誤差三點五。負十二與負三點五也要能解析。另外，0.005、0.0002也要轉。日期如2025年、一月、星期一不應該被轉。單獨位階字：10、100、1000、10000。

In [9]:
import numpy as np
import pandas as pd

df = pd.read_excel('../data/all.xlsx')

selection = ['Option1','Option2','Option3','Option4']

# how many selections in text
count_dict = {0:0, 1:0, 2:0, 3:0, 4:0}

# how many selections in text and correct answer in the selections
corre_dict = {0:0, 1:0, 2:0, 3:0, 4:0}

count = 0

for i in range(df.shape[0]):
    rec = df.iloc[i]
    
    sel = 0
    cor = 0
    
    for s in selection:
        length, _ = longest_common_substrings(replace_cn_numbers(str(rec[s]).strip().lower()), replace_cn_numbers(str(rec['Article']).strip().lower()))
        if length >= 1:
            if selection.index(s) + 1 == rec['Answer']:
                cor = 1 # s is correct answer and in text 
                
            sel = sel + 1
            
    count_dict[sel] = count_dict[sel] + 1
    corre_dict[sel] = corre_dict[sel] + cor
    
    if sel > 0:
        count = count + 1
    else:
        print(rec)
            
print(count)

for i in count_dict:
    if i > 0:
        print(i, count_dict[i], '\t', np.round(count_dict[i]/count*100, 2), '%', '\t', np.round(corre_dict[i]/count*100, 2), '%')

ID                    303
Article                同上
Question    哥哥今年100歲，弟弟幾歲
Option1                48
Option2                50
Option3                98
Option4               100
Answer                  3
Name: 302, dtype: object
ID                              304
Article     星期一時我右手伸出一根手指，每過一天我多伸一隻
Question                七天後我右手有幾根手指
Option1                           4
Option2                           5
Option3                           6
Option4                           7
Answer                            2
Name: 303, dtype: object
ID                      319
Article       有位天才，擅長的科目都滿分
Question    若滿分為100，請問哪個是滿分
Option1                  99
Option2                  98
Option3                 100
Option4                99.1
Answer                    3
Name: 318, dtype: object
ID                                                        961
Article     一九五○年六月廿五日爆發的韓戰，持續三年。一九五三年七月廿七日簽署的「韓戰停戰協定」，由當時...
Question                                            韓戰在西元幾年開戰
Option1                                                  1900
Option2                                                  1950
Option3                                                  1990
Option4                                                  2000
Answer                                                      2
Name: 960, dtype: object
ID                                                       1827
Article     蔡英文總統1號在台灣駭客年會致詞時表示，傳統觀念裡，政府與駭客有些對立，政府必須扮演管制的角...
Question                                               政務委員是誰
Option1                                                   唐三藏
Option2                                                   唐伯虎
Option3                                                    唐鳳
Option4                                                   鳳飛飛
Answer                                                      3
Name: 1826, dtype: object
ID                                                       1937
Article     高雄市左營警分局文自路派出所員警,晚間11點多獲報,左營區崇德路有一部自用車就斜停在路中,員...
Question                                            嫌犯拿出甚麼當證件
Option1                                                    證件
Option2                                                   撲克牌
Option3                                                    名片
Option4                                                    卡片
Answer                                                      2
Name: 1936, dtype: object
ID                                           2418
Article            早期只有男性才具有投票權，經過多年的努力，婦女也享有投票權。
Question    這項投票情形的轉變，若依我國憲\n法的規定來看，主要象徵何項選舉原則的落實
Option1                                        普通
Option2                                        平等
Option3                                        直接
Option4                                       無記名
Answer                                          1
Name: 2417, dtype: object
ID                                                       2426
Article     近年來的電視戲劇節目以不同時代的人物穿越古今，因生活背景差異所產生的劇情跌宕，吸引觀眾。編劇...
Question                           下列各組人物腳色的搭配，何者最不符合所謂的「穿越」？
Option1                                                 李白與杜甫
Option2                                                 項羽與關羽
Option3                                               王安石與康有為
Option4                                               顏真卿與關漢卿
Answer                                                      1
Name: 2425, dtype: object
ID                                            2428
Article     葉似蒲而短闊，兩旁如鋸齒。其實色黃，瓤如鱗甲，形似甜瓜。味甚甘酸，清芬襲人。
Question                               上文所描述的水果\n是
Option1                                         芒果
Option2                                         鳳梨
Option3                                        火龍果
Option4                                        百香果
Answer                                           2
Name: 2427, dtype: object
ID                                                       2435
Article     2005 年近千名南韓農民為了抗議美國等國家對自家出產的農產品提供補貼，並以低價傾銷到南韓，...
Question                                        該項抗議是屬於下列何種訴求
Option1                                                   本土化
Option2                                                  反全球化
Option3                                                 在地全球化
Option4                                                 全球在地化
Answer                                                      2
Name: 2434, dtype: object
ID                                                2438
Article     東北季風盛行時，臺灣會出現沙塵暴，主要是因為蒙古地區的草原被游牧民族過度使用的結果。
Question                     草原因具有下列那一種特性，而導致游牧民族過度使用？
Option1                                            公共財
Option2                                            私有財
Option3                                            劣等財
Option4                                            共有財
Answer                                               4
Name: 2437, dtype: object
ID                              2447
Article     民眾不假他人之手，親自前往投票支持心目中的候選人
Question                 此乃落實下列何項原則？
Option1                         普通原則
Option2                         平等原則
Option3                         直接原則
Option4                        無記名原則
Answer                             3
Name: 2446, dtype: object
ID                     2463
Article       書法刻於石碑者稱之為「碑」
Question    下列選項何者與碑刻文化完全無關
Option1                  臨摹
Option2                  尺牘
Option3                  拓本
Option4                  鑑賞
Answer                    2
Name: 2462, dtype: object
ID                                                       2487
Article     你坐在船上，應該是游山的態度。看看四周物色，隨處可見的山，岸旁的烏桕，河邊的紅蓼和白蘋，漁舍...
Question                                             本段文字旨在強調
Option1                                                  知情識趣
Option2                                                  參觀博覽
Option3                                                  閒情逸致
Option4                                                  林下風致
Answer                                                      3
Name: 2486, dtype: object
ID                                                       3245
Article     操在兗州，招賢納士。有叔姪二人來投曹操：乃穎川穎陰人：姓荀，名彧，字文若，荀昆之子也；舊事袁...
Question                                請問旬彧和旬攸兩人到曹操手下，曹操的心情?
Option1                                                    開心
Option2                                                    難過
Option3                                                    憤怒
Option4                                                    傷心
Answer                                                      1
Name: 3244, dtype: object
ID                                                       4493
Article     如今且說寶玉因見今日人眾，恐秦鐘受了委曲，因默與他商議，要同他往鳳\n姐處來坐。秦鐘道：「她...
Question                               請問根據文章，鳳姐看到寶玉和秦鐘是什麼態度？
Option1                                                    生氣
Option2                                                    愉悅
Option3                                                    冷淡
Option4                                                   沒反應
Answer                                                      2
Name: 4492, dtype: object
ID                                                       4556
Article     至次日，卯正二刻便過來了。那寧國府中婆娘媳婦聞得到齊，只見鳳姐正與\n來升媳婦分派，眾人不敢...
Question                                請問根據文章，鳳姐這一番話是什麼樣的態度？
Option1                                                    嚴厲
Option2                                                    隨和
Option3                                                    友善
Option4                                                    放任
Answer                                                      1
Name: 4555, dtype: object
ID                                                       4774
Article     於是，鳳姐兒方移步前來。將轉過了一重山坡，見兩三個婆子慌慌張張的走 來，見了鳳姐兒，笑說道:...
Question                                        急腳鬼較接近說人個性如何？
Option1                                                   慢郎中
Option2                                                   沒耐性
Option3                                                    細心
Option4                                                    豪爽
Answer                                                      2
Name: 4773, dtype: object
ID                                                       4822
Article     雨村道:「天地生人，除大仁大惡兩種， 餘者皆無大異。若大仁者，則應運而生;大惡者，則應劫而生...
Question                              請問依此觀點，下列哪位著名宗教人物非應運而生？
Option1                                                    耶穌
Option2                                                 釋迦摩尼佛
Option3                                                    撒旦
Option4                                                  真主阿拉
Answer                                                      3
Name: 4821, dtype: object
ID                                                       5240
Article     話說寧國府中都總管來升聞得裏面委請了鳳姐，因傳齊同事人等說道：「如今\n請了西府裏璉二奶奶管...
Question                           請問根據此段文章，寧國府新請來管理內事的人性情如何？
Option1                                                    天真
Option2                                                    友善
Option3                                                    隨和
Option4                                                    嚴格
Answer                                                      4
Name: 5239, dtype: object
ID                                                       5339
Article     說話時，已擺了茶果上來。熙鳳親為捧茶捧果。又見二舅母問她:「月錢放完 了不曾?」熙鳳道:「月...
Question                                       從這段話可知王熙鳳做事如何?
Option1                                                  思慮周全
Option2                                                  粗心大意
Option3                                                  莽撞衝動
Option4                                                  縮首畏尾
Answer                                                      1
Name: 5338, dtype: object
ID                                                       5360
Article     鳳姐因見張材家的在旁，因問道：「你有什麼事？」張材家的忙取帖兒回說道：\n「就是方才車轎圍作...
Question                               請問根據文章，鳳姐對張材家的的請領怎麼處理？
Option1                                                    拒絕
Option2                                                    同意
Option3                                                   不處理
Option4                                                    漠視
Answer                                                      2
Name: 5359, dtype: object
ID                                                       5387
Article     鳳姐兒答應著就出來了，到了尤氏上房坐下。尤氏道:「你冷眼瞧媳婦是怎麼 樣?」鳳姐兒低了半日頭...
Question                                 請問尤氏口中的那件東西，最有可能是什麼？
Option1                                                    座椅
Option2                                                   化妝盒
Option3                                                    棺材
Option4                                                    聘禮
Answer                                                      3
Name: 5386, dtype: object
ID                                                       5611
Article     小南平常見了漂亮而又闊綽的人，心裡就暗想著，就是給人家當一天丫頭也好，這可以和闊人親近親近，...
Question                                根據此段文章，請問下列何者與「闊綽」相異？
Option1                                                    豪華
Option2                                                    寬裕
Option3                                                    清貧
Option4                                                    富裕
Answer                                                      3
Name: 5610, dtype: object
ID                                                       5743
Article     自己這還不該想法子補一點青春之樂嗎？再想到小南子那蘋果一樣的兩頰，肥藕似的手臂，堆雲似的烏髮...
Question                                  根據此段文章，小南子的頭髮是什麼顏色？
Option1                                                     黃
Option2                                                     黑
Option3                                                     金
Option4                                                     紅
Answer                                                      2
Name: 5742, dtype: object
ID                                                       5877
Article     常居士心裡這倒有些後悔。早知道那個姓洪的，不是怎樣一個有錢的人，就不該讓他到家裡來，回頭人家...
Question                                請問根據此段文章，常居士與余氏的關係為何？
Option1                                                    公婆
Option2                                                    夫妻
Option3                                                    姊弟
Option4                                                    父女
Answer                                                      2
Name: 5876, dtype: object
ID                                                       5921
Article     這個日子，白天時間正長著，耳朵裡聽到隔壁人家的時鐘，當當敲了兩下，分 明還是正午，若到七點多...
Question                                   請問根據此段文章，誰對千家詩很熟悉？
Option1                                                   孫悟空
Option2                                                   紅孩兒
Option3                                                   牛魔王
Option4                                                   洪士毅
Answer                                                      4
Name: 5920, dtype: object
ID                                                       5922
Article     這個日子，白天時間正長著，耳朵裡聽到隔壁人家的時鐘，當當敲了兩下，分 明還是正午，若到七點多...
Question                                請問根據此段文章，誰離開屋子到院子裡散步？
Option1                                                   孫悟空
Option2                                                   紅孩兒
Option3                                                   洪士毅
Option4                                                   唐友梅
Answer                                                      3
Name: 5921, dtype: object
ID                                                       6494
Article     高雄市刑大偵四隊破獲「借屍還魂」的竊車集團，查獲兩部贓車，由於本田汽車原廠在全車零件噴灑70...
Question            關於嫌犯辦案順序何者正確？A尋找車禍現場的車子B收購車籍資料C偷同款車輛D改造賣出
Option1                                                  ABCD
Option2                                                  ABDC
Option3                                                  DBCA
Option4                                                  DCAB
Answer                                                      1
Name: 6493, dtype: object
ID                                                       7099
Article     「到了衙門，大人就坐堂，叫把布呈上去，看了一看，就拍著驚堂問道：『你這布那裡來的？』他說：『...
Question                                          請問兩塊布哪裡不一樣?
Option1                                                    花色
Option2                                                    長度
Option3                                                    材質
Option4                                                    價錢
Answer                                                      2
Name: 7098, dtype: object
ID                                                       7237
Article     他雖然也缺錢，但從沒有加入教員的團體內，大家議決罷課，可是不去上課了。政府說“上了課才給錢”...
Question                                    請問大家用罷課的手段希望爭取什麼?
Option1                                                    自由
Option2                                                    薪水
Option3                                                    休假
Option4                                                    地位
Answer                                                      2
Name: 7236, dtype: object
ID                                                       7292
Article     有一回對我說道，「你讀過書麼？」我略略點一點頭。他說，「讀過書，……我便考你一考。茴香豆的茴...
Question                                     請問主人公對於孔乙己是什麼態度?
Option1                                                    輕視
Option2                                                    厭惡
Option3                                                    尊敬
Option4                                                    畏懼
Answer                                                      1
Name: 7291, dtype: object
ID                                                       7293
Article     有幾回，鄰舍孩子聽得笑聲，也趕熱鬧，圍住了孔乙己。他便給他們茴香豆喫，一人一顆。孩子喫完豆，...
Question                                       請問「多乎哉」是詢問什麼的?
Option1                                                    數量
Option2                                                    距離
Option3                                                    時間
Option4                                                    好壞
Answer                                                      1
Name: 7292, dtype: object
ID                                                       7296
Article     次日六點鐘起，先到南門內看了舜井。又出南門，到歷山腳下，看看相傳大舜昔日耕田的地方。及至回店...
Question                                           老殘早上逛了幾個景點
Option1                                                     1
Option2                                                     2
Option3                                                     3
Option4                                                     4
Answer                                                      2
Name: 7295, dtype: object
ID                                                       7297
Article     次日六點鐘起，先到南門內看了舜井。又出南門，到歷山腳下，看看相傳大舜昔日耕田的地方。及至回店...
Question                                     老殘從起床到明湖居共經過幾個小時
Option1                                                     3
Option2                                                     2
Option3                                                     4
Option4                                                     5
Answer                                                      3
Name: 7296, dtype: object
ID                                                       7324
Article     老殘到了次日，想起一千兩銀子放在寓中，總不放心。即到院前大街上找了一家匯票莊，叫個日昇昌字號...
Question                                               文中季節為？
Option1                                                     秋
Option2                                                     冬
Option3                                                     春
Option4                                                     夏
Answer                                                      1
Name: 7323, dtype: object
ID                                                       7331
Article     老殘從鵲華橋往南，緩緩向小布政司街走去。一抬頭，見那牆上貼了一張黃紙，有一尺長，七八寸寬的光...
Question                                      眾人對於白妞說書一事，反應如何
Option1                                                    期待
Option2                                                    無感
Option3                                                    嫌棄
Option4                                                    反對
Answer                                                      1
Name: 7330, dtype: object
ID                                                       7365
Article     自從那日起，又過了幾天，老殘向管事的道：「現在天氣漸寒，貴居停的病也不會再發，明年如有委用之...
Question                                     該戶人家的病，應該好發於何季節？
Option1                                                     春
Option2                                                     夏
Option3                                                     秋
Option4                                                     冬
Answer                                                      2
Name: 7364, dtype: object
ID                                                       7380
Article     但他接連著便覺得很異樣：遇到了平生沒有遇到過的事，不像會有的事，然而的確出現了。他越想越奇，...
Question                                        請問他感受到的是甚麼感覺?
Option1                                                    徬徨
Option2                                                    害怕
Option3                                                    孤單
Option4                                                    心虛
Answer                                                      3
Name: 7379, dtype: object
ID                                                       7403
Article     我向來沒有這樣忍耐的等待過什麼事物，而況這身邊的胖紳士的吁吁的喘氣，這臺上的冬冬皇皇的敲打，...
Question                                    請問對於作者來說，看戲是一種什麼?
Option1                                                    享受
Option2                                                    折磨
Option3                                                    藝術
Option4                                                    高尚
Answer                                                      2
Name: 7402, dtype: object
ID                                                       7432
Article     我們每天的事情大概是掘蚯蚓，掘來穿在銅絲做的小鉤上，伏在河沿上去釣蝦。蝦是水世界裡的呆子，決...
Question                                  請問對於作者來說，釣蝦是一件怎樣的事?
Option1                                                  相當棘手
Option2                                                  難度適中
Option3                                                  輕而易舉
Option4                                                  曠日廢時
Answer                                                      3
Name: 7431, dtype: object
ID                                                       7496

# 問答測試

In [7]:
from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline, logging
logging.set_verbosity_error()

# 模型參考
#https://huggingface.co/models?pipeline_tag=question-answering&sort=trending
#https://huggingface.co/AIFS/Llama3-8x8B-Time-Agents

#model_name= "AIFS/Llama3-8x8B-Time-Agents"
model_name = "deepset/roberta-base-squad2"
#model_name = "google-bert/bert-large-uncased-whole-word-masking-finetuned-squad"

AG = pipeline('question-answering', model=model_name, tokenizer=model_name)
question = "Why is model conversion important?"
context = 'The option to convert models between FARM and transformers gives freedom to the user and let people easily switch between frameworks.'

# 获取答案
res = AG(question=question, context=context)

print(res['answer'])

gives freedom to the user

# 版本2 (預測答案後，從4個選項中找一個跟預測答案最接近的答案當答案)
程式碼執行時間: 0:01:23.806548<br>
共1437題正確；325題錯誤<br>
Accuracy: 0.815550510783201

In [5]:
import pandas as pd
from transformers import pipeline
from text2vec import Similarity
import opencc
import tqdm
from datetime import datetime as dt

# 初始化轉換器
t2s = opencc.OpenCC('t2s')  # 繁體轉簡體
s2t = opencc.OpenCC('s2t')  # 簡體轉繁體

question_answerer = pipeline("question-answering", model="uer/roberta-base-chinese-extractive-qa")

# 定义匹配函数
sim_model = Similarity("shibing624/text2vec-base-multilingual")

def answer_multiple_choice_question(context, question, options, answer):
    # 轉換成簡體
    context_simp = t2s.convert(context)
    question_simp = t2s.convert(question)
    
    result = question_answerer(
        question=question_simp,
        context=context_simp,
    )

    # Get the answer from the QA model
    #answer_simp = s2t.convert(result['answer'])

    predicted_answer = 1
    score = sim_model.get_score(result['answer'], t2s.convert(options[0]))
    
    for i in range(1,len(options)): 
        new_score = sim_model.get_score(result['answer'], t2s.convert(options[i]))
        if new_score > score:
            predicted_answer = i+1
            score = new_score

    is_correct = 1 if predicted_answer == answer else 0
    return is_correct, predicted_answer, result['answer']

# Load your Excel file with pandas
df = pd.read_excel('../data/all.xlsx')

# 新增兩個欄位以存放預測與模型抽取答案
df['predicted_answer'] = None
df['result_answer'] = None

ACC = 0

start_time = dt.now()

for i in tqdm.tqdm(range(len(df))):  # Use the full range len(df) in actual use
    try:
        now = df.iloc[i]
        
        context = str(now['Article'])
        question = str(now['Question'])
        options = [
            str(now["Option1"]),
            str(now["Option2"]),
            str(now["Option3"]),
            str(now["Option4"])
        ]
        answer = int(now["Answer"])
        
        is_correct, predicted_answer, extracted_answer = answer_multiple_choice_question(
            context, question, options, answer
        )

        # 計數
        ACC += is_correct

        # 寫回當前列的新欄位
        df.at[i, 'predicted_answer'] = predicted_answer
        df.at[i, 'result_answer'] = extracted_answer

        if (i+1) % 500 == 0:
            tmp_time = dt.now()
            exe_time = tmp_time - start_time
            print(f"程式碼執行時間: {exe_time}")
            print(f"[{str(dt.now()):.19}] 跑完{i+1}筆資料")
            print(f"目前準確率{ACC}題正確，{i+1-ACC}題錯誤 準確率{ACC/(i+1)}\n")
    except Exception as e:
        tmp_time = dt.now()
        exe_time = tmp_time - start_time
        print(f"程式碼執行時間: {exe_time}")
        print(f"[{str(dt.now()):.19}] 跑完{i}筆資料")
        print(f"共{ACC}題正確；{i - ACC}題錯誤")
        print(f"Accuracy: {ACC / i}\n")
        print(f"Error: {e}")
        time.sleep(5)

end_time = dt.now()
exe_time = end_time - start_time
print(f"程式碼執行時間: {exe_time}")
print(f"共{ACC}題正確；{len(df) - ACC}題錯誤")
print(f"Accuracy: {ACC / len(df)}")

# 輸出含新欄位的結果檔
df.to_excel('../data/all_with_predictions.xlsx', index=False)
print("已輸出：../data/all_with_predictions.xlsx")

WARNING:tensorflow:From C:\Users\leeys\anaconda3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Device set to use cuda:0
  0%|                                                                                 | 9/8550 [00:00<13:14, 10.75it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  6%|████▋                                                                          | 501/8550 [00:39<11:19, 11.84it/s]

程式碼執行時間: 0:00:39.500216
[2025-11-08 21:53:36] 跑完500筆資料
目前準確率369題正確，131題錯誤 準確率0.738

 12%|█████████▏                                                                    | 1001/8550 [01:18<10:07, 12.43it/s]

程式碼執行時間: 0:01:18.535140
[2025-11-08 21:54:15] 跑完1000筆資料
目前準確率770題正確，230題錯誤 準確率0.77

 18%|█████████████▋                                                                | 1503/8550 [01:51<07:37, 15.39it/s]

程式碼執行時間: 0:01:51.139089
[2025-11-08 21:54:47] 跑完1500筆資料
目前準確率1126題正確，374題錯誤 準確率0.7506666666666667

 23%|██████████████████▎                                                           | 2001/8550 [02:32<08:58, 12.15it/s]

程式碼執行時間: 0:02:32.767858
[2025-11-08 21:55:29] 跑完2000筆資料
目前準確率1413題正確，587題錯誤 準確率0.7065

 29%|██████████████████████▊                                                       | 2501/8550 [03:11<07:01, 14.34it/s]

程式碼執行時間: 0:03:11.651203
[2025-11-08 21:56:08] 跑完2500筆資料
目前準確率1689題正確，811題錯誤 準確率0.6756

 35%|███████████████████████████▍                                                  | 3001/8550 [03:49<07:04, 13.07it/s]

程式碼執行時間: 0:03:49.028898
[2025-11-08 21:56:45] 跑完3000筆資料
目前準確率2027題正確，973題錯誤 準確率0.6756666666666666

 41%|███████████████████████████████▉                                              | 3503/8550 [04:30<06:22, 13.21it/s]

程式碼執行時間: 0:04:30.284605
[2025-11-08 21:57:26] 跑完3500筆資料
目前準確率2347題正確，1153題錯誤 準確率0.6705714285714286

 47%|████████████████████████████████████▌                                         | 4001/8550 [05:10<05:38, 13.44it/s]

程式碼執行時間: 0:05:09.994387
[2025-11-08 21:58:06] 跑完4000筆資料
目前準確率2622題正確，1378題錯誤 準確率0.6555

 53%|█████████████████████████████████████████                                     | 4503/8550 [05:44<04:16, 15.76it/s]

程式碼執行時間: 0:05:44.800685
[2025-11-08 21:58:41] 跑完4500筆資料
目前準確率2909題正確，1591題錯誤 準確率0.6464444444444445

 58%|█████████████████████████████████████████████▌                                | 5001/8550 [06:22<04:59, 11.85it/s]

程式碼執行時間: 0:06:22.649476
[2025-11-08 21:59:19] 跑完5000筆資料
目前準確率3201題正確，1799題錯誤 準確率0.6402

 64%|██████████████████████████████████████████████████▏                           | 5501/8550 [07:02<04:21, 11.66it/s]

程式碼執行時間: 0:07:02.445529
[2025-11-08 21:59:59] 跑完5500筆資料
目前準確率3500題正確，2000題錯誤 準確率0.6363636363636364

 70%|██████████████████████████████████████████████████████▊                       | 6003/8550 [07:39<02:36, 16.27it/s]

程式碼執行時間: 0:07:39.070016
[2025-11-08 22:00:35] 跑完6000筆資料
目前準確率3824題正確，2176題錯誤 準確率0.6373333333333333

 76%|███████████████████████████████████████████████████████████▎                  | 6501/8550 [08:15<02:46, 12.31it/s]

程式碼執行時間: 0:08:15.174905
[2025-11-08 22:01:11] 跑完6500筆資料
目前準確率4099題正確，2401題錯誤 準確率0.6306153846153846

 82%|███████████████████████████████████████████████████████████████▊              | 7001/8550 [08:59<02:30, 10.28it/s]

程式碼執行時間: 0:08:59.275610
[2025-11-08 22:01:55] 跑完7000筆資料
目前準確率4432題正確，2568題錯誤 準確率0.6331428571428571

 88%|████████████████████████████████████████████████████████████████████▍         | 7503/8550 [09:35<01:05, 15.91it/s]

程式碼執行時間: 0:09:35.778064
[2025-11-08 22:02:32] 跑完7500筆資料
目前準確率4679題正確，2821題錯誤 準確率0.6238666666666667

 94%|█████████████████████████████████████████████████████████████████████████     | 8003/8550 [10:10<00:41, 13.27it/s]

程式碼執行時間: 0:10:10.493912
[2025-11-08 22:03:07] 跑完8000筆資料
目前準確率4939題正確，3061題錯誤 準確率0.617375

 99%|█████████████████████████████████████████████████████████████████████████████▌| 8501/8550 [10:52<00:04, 10.97it/s]

程式碼執行時間: 0:10:52.763273
[2025-11-08 22:03:49] 跑完8500筆資料
目前準確率5324題正確，3176題錯誤 準確率0.6263529411764706

100%|██████████████████████████████████████████████████████████████████████████████| 8550/8550 [10:57<00:00, 13.01it/s]

程式碼執行時間: 0:10:57.054009
共5365題正確；3185題錯誤
Accuracy: 0.6274853801169591
已輸出：../data/all_with_predictions.xlsx

# 版本3 (預測答案後，從4個選項中找一個跟預測答案最接近的答案當答案，但會排除選項不再article中的選項)
程式碼執行時間: 0:01:27.658340<br>
共1608題正確；154題錯誤<br>
Accuracy: 0.9125993189557321

In [5]:
import pandas as pd
from transformers import pipeline
from text2vec import Similarity
import opencc
import tqdm
from datetime import datetime as dt

# 初始化轉換器
t2s = opencc.OpenCC('t2s')  # 繁體轉簡體
s2t = opencc.OpenCC('s2t')  # 簡體轉繁體

question_answerer = pipeline("question-answering", model="uer/roberta-base-chinese-extractive-qa")

# 定义匹配函数
sim_model = Similarity("shibing624/text2vec-base-multilingual")

def answer_multiple_choice_question(context, question, options, answer):
    # 轉換成簡體
    context_simp = t2s.convert(context)
    question_simp = t2s.convert(question)
    
    result = question_answerer(
        question=question_simp,
        context=context_simp,
    )

    # Get the answer from the QA model
    #answer_simp = s2t.convert(result['answer'])

    count = 0;
    
    for i in range(0,len(options)): 
        if str(options[i]).lower() in str(context).lower():
            count += 1
    
    score = -2

    if(count > 0):
        for i in range(0,len(options)): 
            if str(options[i]).lower() in str(context).lower():
                new_score = sim_model.get_score(result['answer'], t2s.convert(options[i]))
                if new_score > score:
                    predicted_answer = i+1
                    score = new_score
    else:
        for i in range(0,len(options)): 
            new_score = sim_model.get_score(result['answer'], t2s.convert(options[i]))
            if new_score > score:
                predicted_answer = i+1
                score = new_score

    if predicted_answer == answer:
        return 1
    else:
        return 0

# Load your Excel file with pandas
df = pd.read_excel('../data/all.xlsx')

ACC = 0

start_time = dt.now()

for i in tqdm.tqdm(range(len(df))):  # Use the full range len(df) in actual use
    try:
        now = df.iloc[i]
        
        context = str(now['Article'])
        question = str(now['Question'])
        options = [
            str(now["Option1"]),
            str(now["Option2"]),
            str(now["Option3"]),
            str(now["Option4"])
        ]
        answer = int(now["Answer"])
        
        if answer_multiple_choice_question(context, question, options, answer):
            ACC += 1

        if (i+1) % 500 == 0:
            tmp_time = dt.now()
            exe_time = tmp_time - start_time
            print(f"程式碼執行時間: {exe_time}")
            print(f"[{str(dt.now()):.19}] 跑完{i+1}筆資料")
            print(f"目前準確率{ACC}題正確，{i+1-ACC}題錯誤 準確率{ACC/(i+1)}\n")
    except Exception as e:
        tmp_time = dt.now()
        exe_time = tmp_time - start_time
        print(f"程式碼執行時間: {exe_time}")
        print(f"[{str(dt.now()):.19}] 跑完{i}筆資料")
        print(f"共{ACC}題正確；{i - ACC}題錯誤")
        print(f"Accuracy: {ACC / i}\n")
        print(f"Error: {e}")
        time.sleep(5)

end_time = dt.now()
exe_time = end_time - start_time
print(f"程式碼執行時間: {exe_time}")
print(f"共{ACC}題正確；{len(df) - ACC}題錯誤")
print(f"Accuracy: {ACC / len(df)}")

Device set to use cuda:0
  6%|████▋                                                                          | 501/8550 [00:39<08:29, 15.80it/s]

程式碼執行時間: 0:00:38.945200
[2025-10-03 21:10:28] 跑完500筆資料
目前準確率380題正確，120題錯誤 準確率0.76

 12%|█████████                                                                     | 1000/8550 [01:13<07:46, 16.19it/s]

程式碼執行時間: 0:01:13.615679
[2025-10-03 21:11:02] 跑完1000筆資料
目前準確率796題正確，204題錯誤 準確率0.796

 18%|█████████████▋                                                                | 1500/8550 [01:46<06:27, 18.20it/s]

程式碼執行時間: 0:01:46.651525
[2025-10-03 21:11:35] 跑完1500筆資料
目前準確率1160題正確，340題錯誤 準確率0.7733333333333333

 23%|██████████████████▎                                                           | 2002/8550 [02:26<10:43, 10.18it/s]

程式碼執行時間: 0:02:26.212220
[2025-10-03 21:12:15] 跑完2000筆資料
目前準確率1459題正確，541題錯誤 準確率0.7295

 29%|██████████████████████▊                                                       | 2501/8550 [03:07<11:07,  9.07it/s]

程式碼執行時間: 0:03:07.094094
[2025-10-03 21:12:56] 跑完2500筆資料
目前準確率1763題正確，737題錯誤 準確率0.7052

 35%|███████████████████████████▍                                                  | 3001/8550 [03:38<06:27, 14.31it/s]

程式碼執行時間: 0:03:38.326769
[2025-10-03 21:13:27] 跑完3000筆資料
目前準確率2124題正確，876題錯誤 準確率0.708

 41%|███████████████████████████████▉                                              | 3503/8550 [04:13<06:27, 13.03it/s]

程式碼執行時間: 0:04:13.043799
[2025-10-03 21:14:02] 跑完3500筆資料
目前準確率2475題正確，1025題錯誤 準確率0.7071428571428572

 47%|████████████████████████████████████▌                                         | 4002/8550 [04:54<07:06, 10.67it/s]

程式碼執行時間: 0:04:54.501986
[2025-10-03 21:14:43] 跑完4000筆資料
目前準確率2792題正確，1208題錯誤 準確率0.698

 53%|█████████████████████████████████████████                                     | 4503/8550 [05:27<03:39, 18.43it/s]

程式碼執行時間: 0:05:27.467648
[2025-10-03 21:15:16] 跑完4500筆資料
目前準確率3118題正確，1382題錯誤 準確率0.6928888888888889

 58%|█████████████████████████████████████████████▌                                | 5000/8550 [06:03<05:18, 11.15it/s]

程式碼執行時間: 0:06:03.492916
[2025-10-03 21:15:52] 跑完5000筆資料
目前準確率3447題正確，1553題錯誤 準確率0.6894

 64%|██████████████████████████████████████████████████▏                           | 5502/8550 [06:41<03:36, 14.10it/s]

程式碼執行時間: 0:06:41.502196
[2025-10-03 21:16:30] 跑完5500筆資料
目前準確率3784題正確，1716題錯誤 準確率0.688

 70%|██████████████████████████████████████████████████████▋                       | 6001/8550 [07:16<04:02, 10.50it/s]

程式碼執行時間: 0:07:16.456624
[2025-10-03 21:17:05] 跑完6000筆資料
目前準確率4147題正確，1853題錯誤 準確率0.6911666666666667

 76%|███████████████████████████████████████████████████████████▎                  | 6501/8550 [07:53<03:58,  8.61it/s]

程式碼執行時間: 0:07:53.404021
[2025-10-03 21:17:42] 跑完6500筆資料
目前準確率4454題正確，2046題錯誤 準確率0.6852307692307692

 82%|███████████████████████████████████████████████████████████████▉              | 7002/8550 [08:33<01:53, 13.64it/s]

程式碼執行時間: 0:08:33.060750
[2025-10-03 21:18:22] 跑完7000筆資料
目前準確率4799題正確，2201題錯誤 準確率0.6855714285714286

 88%|████████████████████████████████████████████████████████████████████▍         | 7502/8550 [09:17<01:48,  9.69it/s]

程式碼執行時間: 0:09:16.965859
[2025-10-03 21:19:06] 跑完7500筆資料
目前準確率5081題正確，2419題錯誤 準確率0.6774666666666667

 94%|████████████████████████████████████████████████████████████████████████▉     | 8001/8550 [10:02<00:42, 12.93it/s]

程式碼執行時間: 0:10:02.709494
[2025-10-03 21:19:52] 跑完8000筆資料
目前準確率5373題正確，2627題錯誤 準確率0.671625

 99%|█████████████████████████████████████████████████████████████████████████████▌| 8502/8550 [10:39<00:03, 13.01it/s]

程式碼執行時間: 0:10:39.562275
[2025-10-03 21:20:28] 跑完8500筆資料
目前準確率5785題正確，2715題錯誤 準確率0.6805882352941176

100%|██████████████████████████████████████████████████████████████████████████████| 8550/8550 [10:43<00:00, 13.29it/s]

程式碼執行時間: 0:10:43.230180
共5829題正確；2721題錯誤
Accuracy: 0.6817543859649123

In [10]:
import pandas as pd
import torch
from transformers import pipeline, AutoTokenizer, AutoModel
import torch.nn.functional as F
import numpy as np
import tqdm
from datetime import datetime as dt
#from datasets import Dataset

# Check if GPU is available and set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load QA model on the specified device
model_name = "deepset/roberta-base-squad2"
AG = pipeline('question-answering', model=model_name, tokenizer=model_name, device=0 if device.type == "cuda" else -1)

# Load embedding model and move it to GPU
embed_model_name = 'sentence-transformers/all-MiniLM-L6-v2'
tokenizer = AutoTokenizer.from_pretrained(embed_model_name)
model = AutoModel.from_pretrained(embed_model_name).to(device)

def answer_multiple_choice_question(text, question, options, answer):
    # Get the answer from the QA model
    result = AG(question=question, context=text)
    res_answer = result['answer']
    # print(f"Model Answer:{res_answer} Answer:{options[answer-1]}")

    options.append(res_answer)  # Add the model's answer to the options
    encoded_input = tokenizer(options, padding=True, truncation=True, return_tensors='pt').to('cuda' if torch.cuda.is_available() else 'cpu')
    with torch.no_grad():
        model_output = model(**encoded_input)
    sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])
    sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)

    similarities = []
    for i in range(len(options) - 1):
        if options[i].lower() in text.lower():
            cosine_sim = F.cosine_similarity(sentence_embeddings[i].unsqueeze(0), sentence_embeddings[-1].unsqueeze(0))
            cosine_sim = cosine_sim.item()  # Convert tensor to Python float
        else:
            cosine_sim = 0.0
        similarities.append(cosine_sim)

    best_option_index = np.argmax(similarities)
    if best_option_index + 1 == answer:
        return 1
    else:
        return 0

ACC = 0

start_time = dt.now()

for i in tqdm.tqdm(range(len(df))):  # Use the full range len(df) in actual use
    try:
        now = df.iloc[i]

        text = str(now['article'])
        question = str(now['question'])
        options = [
            str(now["selection1"]),
            str(now["selection2"]),
            str(now["selection3"]),
            str(now["selection4"])]
        answer = int(now["correct_answer"])

        if answer_multiple_choice_question(text, question, options, answer):
            ACC += 1

        if (i + 1) % 500 == 0:
            tmp_time = dt.now()
            exe_time = tmp_time - start_time
            print(f"\u7a0b\u5f0f\u78b0\u57f7\u884c\u6642\u9593: {exe_time}")
            print(f"[{str(dt.now()):.19}] \u8dd1\u5b8c{i + 1}\u7b46\u8cc7\u6599")
            print(f"\u76ee\u524d\u6e96\u78ba\u7387{ACC}\u984c\u6b63\u78ba\uff0c{i + 1 - ACC}\u984c\u932f\u8aa4 \u6e96\u78ba\u7387{ACC / (i + 1)}\n")
    except Exception as e:
        tmp_time = dt.now()
        exe_time = tmp_time - start_time
        print(f"\u7a0b\u5f0f\u78b0\u57f7\u884c\u6642\u9593: {exe_time}")
        print(f"[{str(dt.now()):.19}] \u8dd1\u5b8c{i}\u7b46\u8cc7\u6599")
        print(f"\u5171{ACC}\u984c\u6b63\u78ba\uff1b{i - ACC}\u984c\u932f\u8aa4")
        print(f"Accuracy: {ACC / i}\n")
        print(f"Error: {e}")
        time.sleep(5)

end_time = dt.now()
exe_time = end_time - start_time
print(f"程式碼執行時間: {exe_time}")
print(f"共{ACC}題正確；{len(df) - ACC}題錯誤")
print(f"Accuracy: {ACC / len(df)}")

Using device: cuda

 29%|██████████████████████▌                                                        | 504/1762 [00:26<00:52, 24.16it/s]

程式碰執行時間: 0:00:26.022809
[2025-08-31 15:53:12] 跑完500筆資料
目前準確率445題正確，55題錯誤 準確率0.89

 57%|████████████████████████████████████████████▍                                 | 1003/1762 [00:51<00:34, 21.77it/s]

程式碰執行時間: 0:00:51.240671
[2025-08-31 15:53:37] 跑完1000筆資料
目前準確率911題正確，89題錯誤 準確率0.911

 85%|██████████████████████████████████████████████████████████████████▌           | 1505/1762 [01:17<00:10, 23.42it/s]

程式碰執行時間: 0:01:17.427488
[2025-08-31 15:54:03] 跑完1500筆資料
目前準確率1368題正確，132題錯誤 準確率0.912

100%|██████████████████████████████████████████████████████████████████████████████| 1762/1762 [01:31<00:00, 19.36it/s]

程式碼執行時間: 0:01:31.036561
共1608題正確；154題錯誤
Accuracy: 0.9125993189557321

# 版本4 (預測答案後，從4個選項中找一個跟預測答案最接近的答案當答案，但會排除選項不再article中的選項，若只有一個候選選項，則直接預測該選項)
程式碼執行時間: 0:01:27.196759<br>
共1612題正確；150題錯誤<br>
Accuracy: 0.9148694665153235

In [12]:
# Load your Excel file with pandas
df = pd.read_excel('test_data.xlsx')

selection = ['selection1','selection2','selection3','selection4']

count_dict = {0:0, 1:0, 2:0, 3:0, 4:0}
n_sel = []

count = 0

for i in range(df.shape[0]):
    rec = df.iloc[i]
    
    sel = 0
    
    for s in selection:
        if rec[s].lower().strip() in rec['article'].lower().strip():
            sel = sel + 1
            
    count_dict[sel] = count_dict[sel] + 1
    n_sel.append(sel)
    
    if sel > 0:
        count = count + 1
            
print(count)

for i in count_dict:
    print(i, count_dict[i], '\t', np.round(count_dict[i]/count*100, 1), '%')
    
print(n_sel[:15])

1762
0 0 	 0.0 %
1 998 	 56.6 %
2 326 	 18.5 %
3 164 	 9.3 %
4 274 	 15.6 %
[1, 1, 2, 3, 2, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1]

In [14]:
import pandas as pd
import torch
from transformers import pipeline, AutoTokenizer, AutoModel
import torch.nn.functional as F
import numpy as np
from datetime import datetime as dt
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
from tqdm import tqdm

# Define the mean pooling function
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0]  # First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

# Load QA model
model_name = "deepset/roberta-base-squad2"
#model_name = "google-bert/bert-large-uncased-whole-word-masking-finetuned-squad"
#model_name = "timpal0l/mdeberta-v3-base-squad2"

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

AG = pipeline('question-answering', model=model_name, tokenizer=model_name, device=0 if torch.cuda.is_available() else -1)

# Load embedding model
embed_model_name = 'sentence-transformers/all-MiniLM-L6-v2'
tokenizer = AutoTokenizer.from_pretrained(embed_model_name)
model = AutoModel.from_pretrained(embed_model_name).to(device)

def answer_multiple_choice_question(data):
    text = data['article'].strip()
    question = data['question']
    options = [
        data["selection1"].strip(),
        data["selection2"].strip(),
        data["selection3"].strip(),
        data["selection4"].strip()
    ]
    answer = data["correct_answer"]

    # Get the answer from the QA model
    result = AG(question=question, context=text)
    res_answer = result['answer']
    
    options.append(res_answer)  # Add the model's answer to the options
    encoded_input = tokenizer(options, padding=True, truncation=True, return_tensors='pt').to(device)
    with torch.no_grad():
        model_output = model(**encoded_input)
    sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])
    sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)

    similarities = []
    for i in range(len(options) - 1):
        if options[i].lower() in text.lower().strip():
            if data['n_sel'] == 1:
                cosine_sim = 1.0
            else:
                cosine_sim = F.cosine_similarity(sentence_embeddings[i].unsqueeze(0), sentence_embeddings[-1].unsqueeze(0))
                cosine_sim = cosine_sim.item() # Convert tensor to Python float
        else:
            cosine_sim = 0.0
            
        similarities.append(cosine_sim)

    best_option_index = np.argmax(similarities)
    
    if best_option_index + 1 == answer:
        return 1
    else:
        if data['n_sel'] == 1:
            print(data['selection1'], '/', data['selection2'], '/', data['selection3'], '/', data['selection4'], '/', data['correct_answer'], '-->', best_option_index + 1)
        else:
            return 0

# Load your Excel file with pandas
df = pd.read_excel('test_data.xlsx')
df['n_sel'] = n_sel

# Convert pandas DataFrame to Hugging Face dataset
dataset = Dataset.from_pandas(df)

# Use a DataLoader for efficient batching
data_loader = DataLoader(dataset, batch_size=8, shuffle=False)

ACC = 0
results = []

start_time = dt.now()

for batch in tqdm(data_loader):
    for i in range(len(batch['article'])):
        try:
            data = {key: batch[key][i] for key in batch}
            if answer_multiple_choice_question(data):
                ACC += 1
                results.append('Correct')
            else:
                results.append('Wrong')
        except Exception as e:
            print(f"Error: {e}")

end_time = dt.now()
exe_time = end_time - start_time
print(f"程式碼執行時間: {exe_time}")
print(f"共{ACC}題正確；{len(dataset) - ACC}題錯誤")
print(f"Accuracy: {ACC / len(dataset)}")

cuda

100%|████████████████████████████████████████████████████████████████████████████████| 221/221 [01:22<00:00,  2.66it/s]

程式碼執行時間: 0:01:22.969553
共1612題正確；150題錯誤
Accuracy: 0.9148694665153235

In [6]:
# Create the cross-tabulation
cross_tab = pd.crosstab(n_sel, results)
cross_tab['%'] = cross_tab['Wrong'] / (cross_tab['Correct'] + cross_tab['Wrong'])

print(cross_tab)

col_0  Correct  Wrong         %
row_0
1          998      0  0.000000
2          274     52  0.159509
3          127     37  0.225610
4          213     61  0.222628

# 版本5 (預測答案後，從4個選項中找一個跟預測答案最接近的答案當答案，但會排除選項不再article中的選項，若只有一個候選選項，則直接預測該選項，更換預測模型)
程式碼執行時間: 0:02:48.098942<br>
共1616題正確；146題錯誤<br>
Accuracy: 0.9171396140749148

In [15]:
import pandas as pd
import torch
from transformers import pipeline, AutoTokenizer, AutoModel
import torch.nn.functional as F
import numpy as np
from datetime import datetime as dt
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
import tqdm

# Define the mean pooling function
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0]  # First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

# Load QA model
#model_name = "deepset/roberta-base-squad2"
#model_name = "google-bert/bert-large-uncased-whole-word-masking-finetuned-squad"
model_name = "timpal0l/mdeberta-v3-base-squad2"

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

AG = pipeline('question-answering', model=model_name, tokenizer=model_name, device=0 if torch.cuda.is_available() else -1)

# Load embedding model
embed_model_name = 'sentence-transformers/all-MiniLM-L6-v2'
tokenizer = AutoTokenizer.from_pretrained(embed_model_name)
model = AutoModel.from_pretrained(embed_model_name).to(device)

def answer_multiple_choice_question(data):
    text = data['article'].strip()
    question = data['question']
    options = [
        data["selection1"].strip(),
        data["selection2"].strip(),
        data["selection3"].strip(),
        data["selection4"].strip()
    ]
    answer = data["correct_answer"]

    # Get the answer from the QA model
    result = AG(question=question, context=text)
    res_answer = result['answer']
    
    options.append(res_answer)  # Add the model's answer to the options
    encoded_input = tokenizer(options, padding=True, truncation=True, return_tensors='pt').to(device)
    with torch.no_grad():
        model_output = model(**encoded_input)
    sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])
    sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)

    similarities = []
    for i in range(len(options) - 1):
        if options[i].lower() in text.lower().strip():
            if data['n_sel'] == 1:
                cosine_sim = 1.0
            else:
                cosine_sim = F.cosine_similarity(sentence_embeddings[i].unsqueeze(0), sentence_embeddings[-1].unsqueeze(0))
                cosine_sim = cosine_sim.item() # Convert tensor to Python float
        else:
            cosine_sim = 0.0
            
        similarities.append(cosine_sim)

    best_option_index = np.argmax(similarities)
    
    if best_option_index + 1 == answer:
        return 1
    else:
        if data['n_sel'] == 1:
            print(data['selection1'], '/', data['selection2'], '/', data['selection3'], '/', data['selection4'], '/', data['correct_answer'], '-->', best_option_index + 1)
        else:
            return 0

# Load your Excel file with pandas
df = pd.read_excel('test_data.xlsx')
df['n_sel'] = n_sel

# Convert pandas DataFrame to Hugging Face dataset
dataset = Dataset.from_pandas(df)

# Use a DataLoader for efficient batching
data_loader = DataLoader(dataset, batch_size=8, shuffle=False)

ACC = 0
results = []

start_time = dt.now()

for batch in tqdm.tqdm(data_loader):
    for i in range(len(batch['article'])):
        try:
            data = {key: batch[key][i] for key in batch}
            if answer_multiple_choice_question(data):
                ACC += 1
                results.append('Correct')
            else:
                results.append('Wrong')
        except Exception as e:
            print(f"Error: {e}")

end_time = dt.now()
exe_time = end_time - start_time
print(f"程式碼執行時間: {exe_time}")
print(f"共{ACC}題正確；{len(dataset) - ACC}題錯誤")
print(f"Accuracy: {ACC / len(dataset)}")

cuda

100%|████████████████████████████████████████████████████████████████████████████████| 221/221 [03:06<00:00,  1.18it/s]

程式碼執行時間: 0:03:06.515291
共1616題正確；146題錯誤
Accuracy: 0.9171396140749148

# 版本6 (直接請T5-Flan-T5 Base 模型預測結果 (Zero-Shot))
Accuracy: 0.9188422247446084

In [16]:
import pandas as pd
pd.set_option('display.max_rows', None)

import warnings
#warnings.simplefilter("ignore")

train = pd.read_excel('training_data.xlsx')
test = pd.read_excel('test_data.xlsx')
dev = train.sample(n=1000, random_state=1)

test.head()

,question_id,article,question,selection1,selection2,selection3,selection4,correct_answer
0,4967,The Center for Advanced European Survey and Re...,Where is the sensor planned to be installed?,On the rim of the tire,Inside the tire,In the tread groove of the tire where it conta...,In the sidewall of the tire,3
1,3465,When organisms evolve from ocean to freshwater...,What type of organism were the fossils identif...,bacteria,eukaryotes,archaea,prokaryotes,2
2,7649,What is LCD? Liquid crystal is a material that...,What is the abbreviation of liquid crystal dis...,QLED,OLED,LED,LCD,4
3,3881,Physicians generally agree that sex improves m...,Which country's researchers mentioned in a rep...,Germany,United States,Japan,South Korea,1
4,3726,The government has recently begun to promote c...,What has been a hot topic in Taiwan for the la...,opening of health insurance and medical data,development of semiconductor,opening of the Forbidden City's cultural resou...,opening of high school exams,1

In [17]:
import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration

device = "cuda:0" if torch.cuda.is_available() else "cpu"
print(device)

# Load model
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

try:
    # 加载模型
    tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
    model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base").to(device)
    print("Model and tokenizer loaded successfully!")
except Exception as e:
    print(f"Error loading model or tokenizer: {e}")
    print("Please check your internet connection, available disk space, or Hugging Face cache.")

cuda:0
Model and tokenizer loaded successfully!

In [18]:
preamble = \
    'Use the articles about the question, '\
    'Answer the following question by outputting the letters A, B, C, D, '\
    'in order of the most likely to be correct to the to least likely to be correct.'
preamble

'Use the articles about the question, Answer the following question by outputting the letters A, B, C, D, in order of the most likely to be correct to the to least likely to be correct.'

In [19]:
from string import Template

preamble = \
    'Use the articles about the question, '\
    'Answer the following question by outputting the letters A, B, C, D, '\
    'in order of the most likely to be correct to the to least likely to be correct.'

template = Template('$preamble\n\n$article\n\nThe question is listed below.\n$question\n\nA) $a\nB) $b\nC) $c\nD) $d')

In [20]:
from string import Template

preamble = \
    'Using the following article '\
    'to Answer the question by outputting only one letter from A, B, C, or D '\
    'that you believe is the most likely to be correct.'

template = Template('$preamble\n\n$article\n\nThe question is listed below.\n$question\n\nA) $a\nB) $b\nC) $c\nD) $d')

In [21]:
def format_input(df, idx):   
    article = df.loc[idx, 'article']
    question = df.loc[idx, 'question']
    a = df.loc[idx, 'selection1']
    b = df.loc[idx, 'selection2']
    c = df.loc[idx, 'selection3']
    d = df.loc[idx, 'selection4']

    input_text = template.substitute(
        preamble=preamble,article=article, question=question, a=a, b=b, c=c, d=d)
    
    return input_text

print(format_input(test, 0))

Using the following article to Answer the question by outputting only one letter from A, B, C, or D that you believe is the most likely to be correct.

The Center for Advanced European Survey and Research (CAESAR) has developed a new measurement sensor that can alert drivers to road conditions. Although cars have been equipped with safety devices such as ABS systems for many years, they have functions such as preventing tire locking or slipping, properly distributing tire grip, and maintaining vehicle driving stability. However, these devices still have a major drawback, which is that the system responds too slowly, and the system does not display the warning until the brakes are applied or the vehicle is already spinning. The sensor designed by Kaiser Research Center has the ability to continuously measure tire grip, identify dangerous road conditions early, shorten braking time, and quickly restore the balance system. In order for the sensor to fully grasp the ground conditions, a large amount of data is required. It is estimated that about 40,000 measurements per second are required. Especially the speed of the new tire has reached 330 kilometers per hour, which is a big challenge for researchers. According to a French research report, excessive braking time and improper tire pressure account for 12% of vehicle accidents. Therefore, the sensor developed by Kaiser Research Center must not only measure the friction of the tire contacting the ground, but also measure the inflation of the inner tube. quantity. The researchers plan to design a sensor several square millimeters in size that will be installed in the tread groove of the tire where it contacts the ground. The antenna located above the tire continuously transmits high-frequency signals to the sensor while driving. After the sensor receives the information about changes in road conditions, it sends it back to the antenna, and the measurement system in the car conducts further analysis. The tire tread grooves change their shape according to road conditions, and the sensors convert these mechanical characteristics into electronic signals. For example, on hydrophobic sections, the sensors can identify water droplets in front of the tires. The vehicle operating system only needs to adjust according to the displayed measurement curve, and driving safety is greatly improved. In the early stages of development, after tire testing and testing on special road sections, the signal transmission between the sensor and the antenna was smooth. It is estimated that it will take another seven years for tire sensors to be mass-produced, and by then the first-generation sensors will be installed on high-end RVs.

The question is listed below.
Where is the sensor planned to be installed?

A) On the rim of the tire
B) Inside the tire
C) In the tread groove of the tire where it contacts the ground
D) In the sidewall of the tire

In [25]:
inputs = tokenizer(format_input(train, 1), return_tensors="pt").to(device)
outputs = model.generate(**inputs, max_new_tokens=1)
answer = tokenizer.batch_decode(outputs, skip_special_tokens=True)

print(answer)

['D']

In [22]:
import tqdm
from sklearn.metrics import classification_report, accuracy_score

### 对验证集进行输出
for idx in tqdm.tqdm(dev.index):
    inputs = tokenizer(format_input(dev, idx), return_tensors="pt").to(device)
    outputs = model.generate(**inputs, max_new_tokens=1)
    answer = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    dev.loc[idx, 'prediction'] = answer[0]
    
result = dev["prediction"].str[0].map({"A": 1, "B": 2, "C": 3, "D": 4}).fillna(1)
y_true = dev['correct_answer']
print(classification_report(y_true,result))
print(f"Accuracy: {accuracy_score(y_true,result)}")

100%|██████████████████████████████████████████████████████████████████████████████| 1000/1000 [01:18<00:00, 12.76it/s]

              precision    recall  f1-score   support

           1       0.94      0.91      0.92       249
           2       0.91      0.94      0.92       270
           3       0.94      0.91      0.93       250
           4       0.89      0.92      0.91       231

    accuracy                           0.92      1000
   macro avg       0.92      0.92      0.92      1000
weighted avg       0.92      0.92      0.92      1000

Accuracy: 0.921

In [23]:
import tqdm
from sklearn.metrics import classification_report

# 对測試集进行输出
for idx in tqdm.tqdm(test.index):
    inputs = tokenizer(format_input(test, idx), return_tensors="pt").to(device)
    outputs = model.generate(**inputs, max_new_tokens=1)
    answer = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    test.loc[idx, 'Predicted_Results'] = answer[0]
    
result = test["Predicted_Results"].str[0].map({"A": 1, "B": 2, "C": 3, "D": 4}).fillna(1)
y_true = test['correct_answer']
print(classification_report(y_true,result))
print(f"Accuracy: {accuracy_score(y_true,result)}")

100%|██████████████████████████████████████████████████████████████████████████████| 1762/1762 [02:18<00:00, 12.72it/s]

              precision    recall  f1-score   support

           1       0.95      0.90      0.92       443
           2       0.93      0.93      0.93       430
           3       0.90      0.92      0.91       451
           4       0.91      0.94      0.93       438

    accuracy                           0.92      1762
   macro avg       0.92      0.92      0.92      1762
weighted avg       0.92      0.92      0.92      1762

Accuracy: 0.9216799091940976

In [35]:
test["Predicted_Results"] = test["Predicted_Results"].map({"A":1,"B":2,"C":3,"D":4})
test[['question_id', 'Predicted_Results']].to_csv('Final_Results.csv', index=False)